// Copyright (c) 2026 OceanBase. Licensed under the Apache License, Version 2.0.
use seekdb_extension::sys::*;
use std::collections::BTreeMap;
use std::mem::{align_of, offset_of, size_of};
use std::{fs, path::Path, process::Command};

#[test]
fn layouts_match_public_c_headers() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let temporary = std::env::temp_dir().join(format!(
        "seekdb-sdk-layout-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&temporary).unwrap();
    let binary = temporary.join(if cfg!(windows) {
        "layout.exe"
    } else {
        "layout"
    });
    let compiler = std::env::var_os("CC").unwrap_or_else(|| "cc".into());
    let compiled = Command::new(compiler)
        .arg("-std=c11")
        .arg("-I")
        .arg(root.join("../../include"))
        .arg(root.join("tests/layout.c"))
        .arg("-o")
        .arg(&binary)
        .output()
        .unwrap();
    assert!(
        compiled.status.success(),
        "C ABI probe compile failed: {}",
        String::from_utf8_lossy(&compiled.stderr)
    );
    let output = Command::new(&binary).output().unwrap();
    // Remove only this test's exact generated executable and empty directory.
    fs::remove_file(&binary).unwrap();
    fs::remove_dir(&temporary).unwrap();
    assert!(output.status.success());
    let c: BTreeMap<String, usize> = String::from_utf8(output.stdout)
        .unwrap()
        .lines()
        .map(|line| {
            let (key, value) = line.split_once('=').unwrap();
            (key.to_owned(), value.parse().unwrap())
        })
        .collect();
    let mut rust = BTreeMap::new();
    macro_rules! layout {
        ($name:ident, $t:ty, $($field:ident),+ $(,)?) => {
            rust.insert(concat!(stringify!($name), ".size").to_owned(), size_of::<$t>());
            rust.insert(concat!(stringify!($name), ".align").to_owned(), align_of::<$t>());
            $(rust.insert(concat!(stringify!($name), ".", stringify!($field)).to_owned(), offset_of!($t, $field));)+
        };
    }
    layout!(Version, Version, major, minor, patch);
    layout!(
        CustomPathRequestV3,
        CustomPathRequestV3,
        v2,
        input_plans,
        plan_count,
        execution,
        input_offsets,
        reserved
    );
    layout!(
        CustomPathRequestV2,
        CustomPathRequestV2,
        v1,
        inputs,
        input_count,
        output_count,
        outputs,
        reserved
    );
    layout!(
        CustomColumn,
        CustomColumn,
        struct_size,
        flags,
        encoding,
        sql_type,
        collation,
        precision,
        scale,
        reserved_word,
        type_id,
        reserved
    );
    layout!(
        CustomSchema,
        CustomSchema,
        struct_size,
        column_count,
        columns,
        reserved
    );
    layout!(
        CustomContextV2,
        CustomContextV2,
        v1,
        inputs,
        output,
        reserved
    );
    layout!(CustomContextV3, CustomContextV3, v2, rescan_input, reserved);
    layout!(
        CustomContextV4,
        CustomContextV4,
        v3,
        bind_rescan_input,
        reserved
    );
    layout!(
        InputBinding,
        InputBinding,
        parameter,
        source_input,
        source_column,
        target_input
    );
    layout!(
        CustomPathRequestV4,
        CustomPathRequestV4,
        v3,
        bindings,
        binding_count,
        reserved_word,
        reserved
    );
    layout!(
        CustomRow,
        CustomRow,
        struct_size,
        column_count,
        values,
        reserved
    );
    layout!(
        CustomContext,
        CustomContext,
        struct_size,
        input_count,
        output_column_count,
        reserved_word,
        host_context,
        next_input,
        emit,
        check_interrupt,
        reserved
    );
    layout!(
        CustomExecutor,
        CustomExecutor,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        open,
        next,
        rescan,
        close,
        reserved
    );
    layout!(
        ServerDevManifest,
        ServerDevManifest,
        v1,
        bridge_version,
        host_build_id_size,
        host_build_id,
        reserved
    );
    rust.insert("cap.server_dev".to_owned(), SERVER_DEV as usize);
    layout!(
        CustomPathRequest,
        CustomPathRequest,
        v1,
        service_id,
        service_major,
        minimum_minor,
        plan,
        plan_size,
        flags,
        operator_cost,
        reserved
    );
    layout!(
        PathRequest,
        PathRequest,
        struct_size,
        kind,
        input_index,
        reserved_word,
        reserved
    );
    layout!(
        CandidateContextV2,
        CandidateContextV2,
        v1,
        current_count,
        build,
        get_error,
        reserved
    );
    layout!(
        CandidateContextV3,
        CandidateContextV3,
        v2,
        root,
        plan,
        child,
        expression,
        describe_expression,
        argument,
        reserved
    );
    layout!(
        CandidateContextV4,
        CandidateContextV4,
        v3,
        query,
        target,
        reserved
    );
    layout!(
        CandidateContextV5,
        CandidateContextV5,
        v4,
        plan_semantics,
        expression_semantics,
        scope,
        column_count,
        column,
        reserved
    );
    layout!(
        CandidateContextV6,
        CandidateContextV6,
        v5,
        binding_count,
        binding,
        reserved
    );
    layout!(
        CandidateContextV7,
        CandidateContextV7,
        v6,
        sort_info,
        sort_key,
        reserved
    );
    layout!(
        CandidateContextV8,
        CandidateContextV8,
        v7,
        value_info,
        reserved
    );
    layout!(ValueInfo, ValueInfo, struct_size, flags, reserved);
    layout!(
        SortInfo,
        SortInfo,
        struct_size,
        flags,
        key_count,
        prefix_key_count,
        partition_key_count,
        topn_expression,
        topk_limit_expression,
        topk_offset_expression,
        hash_expression,
        reserved_word,
        reserved
    );
    layout!(
        PlanSemantics,
        PlanSemantics,
        struct_size,
        relation_kind,
        flags,
        reserved_word,
        reserved
    );
    layout!(
        ExprSemantics,
        ExprSemantics,
        struct_size,
        comparison_kind,
        value_kind,
        flags,
        reserved
    );
    layout!(
        QueryInfo,
        QueryInfo,
        struct_size,
        statement_type,
        flags,
        target_count,
        reserved
    );
    layout!(
        PlanInfo,
        PlanInfo,
        struct_size,
        operator_type,
        child_count,
        join_type,
        expression_counts,
        reserved_word,
        cost,
        rows,
        width,
        reserved
    );
    layout!(
        ExprInfo,
        ExprInfo,
        struct_size,
        expression_type,
        sql_type,
        flags,
        argument_count,
        collation,
        precision,
        scale,
        table_id,
        column_id,
        type_id,
        reserved
    );
    layout!(
        CandidateInfo,
        CandidateInfo,
        struct_size,
        operator_type,
        cost,
        rows,
        width,
        reserved
    );
    layout!(
        CandidateContext,
        CandidateContext,
        struct_size,
        candidate_count,
        host_context,
        get,
        select,
        continuation,
        next,
        reserved
    );
    layout!(
        CandidateService,
        CandidateService,
        struct_size,
        spi_major,
        spi_minor,
        mode,
        invoke,
        reserved
    );
    layout!(
        CatalogBuildContext,
        CatalogBuildContext,
        struct_size,
        reserved_word,
        tenant_id,
        database_id,
        owner_id,
        extension_name,
        extension_version,
        host_context,
        create_routine,
        reserved
    );
    layout!(CatalogServiceV2, CatalogServiceV2, v1, build, reserved);
    layout!(
        CatalogBuildContextV2,
        CatalogBuildContextV2,
        v1,
        lookup_routine,
        reserved
    );
    layout!(
        CatalogContext,
        CatalogContext,
        struct_size,
        reserved_word,
        tenant_id,
        database_id,
        owner_id,
        extension_name,
        extension_version,
        host_context,
        emit_sql,
        reserved
    );
    layout!(
        CatalogService,
        CatalogService,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        prepare,
        reserved
    );
    layout!(
        OptimizerHookDescriptor,
        OptimizerHookDescriptor,
        struct_size,
        object_id,
        hook_point,
        priority,
        reserved_word,
        flags,
        implementation,
        reserved
    );
    layout!(
        OptimizerInfo,
        OptimizerInfo,
        struct_size,
        statement_kind,
        database_id,
        user_id,
        reserved
    );
    layout!(
        OptimizerContext,
        OptimizerContext,
        struct_size,
        info,
        continuation,
        next,
        reserved
    );
    layout!(
        OptimizerService,
        OptimizerService,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        invoke,
        reserved
    );
    layout!(
        VersionRange,
        VersionRange,
        struct_size,
        minimum_inclusive,
        maximum_exclusive,
        reserved
    );
    layout!(
        ServiceProvide,
        ServiceProvide,
        struct_size,
        service_id,
        version,
        service,
        capabilities,
        reserved
    );
    layout!(
        ServiceRequire,
        ServiceRequire,
        struct_size,
        service_id,
        version_range,
        service_slot,
        optional,
        reserved_bytes,
        required_capabilities,
        reserved
    );
    layout!(
        HostApiV1,
        HostApiV1,
        struct_size,
        abi_major,
        abi_minor,
        host_handle,
        alloc,
        free,
        log,
        acquire_service,
        release_service,
        begin_registration,
        register_service,
        commit_registration,
        abort_registration,
        reserved
    );
    layout!(
        HostApiV2,
        HostApiV2,
        host,
        registration_spi_major,
        registration_spi_minor,
        register_extension,
        registration_reserved
    );
    layout!(
        OwnedBytesV1,
        OwnedBytesV1,
        struct_size,
        alignment,
        size,
        data,
        owner,
        release,
        reserved
    );
    layout!(
        HostApiV3,
        HostApiV3,
        v2,
        memory_spi_major,
        memory_spi_minor,
        allocate_owned_bytes,
        memory_reserved
    );
    layout!(
        Manifest,
        Manifest,
        struct_size,
        abi_major,
        abi_minor,
        plugin_id,
        vendor,
        version,
        build_id,
        catalog_version,
        data_format_version,
        capabilities,
        provides,
        provides_count,
        required_services,
        required_services_count,
        init,
        start,
        stop,
        deinit,
        reserved
    );
    layout!(
        Implementation,
        Implementation,
        struct_size,
        service_id,
        version_range,
        required_capabilities,
        reserved
    );
    layout!(
        FunctionV1,
        FunctionV1,
        struct_size,
        object_id,
        sql_name,
        minimum_arity,
        maximum_arity,
        static_result_type_id,
        flags,
        implementation,
        reserved
    );
    layout!(
        TypeDescriptor,
        TypeDescriptor,
        struct_size,
        object_id,
        sql_name,
        physical_format_id,
        physical_format_version,
        reserved_word,
        flags,
        codec_service,
        reserved
    );
    layout!(
        CastDescriptor,
        CastDescriptor,
        struct_size,
        object_id,
        source_type_id,
        target_type_id,
        context,
        cost,
        flags,
        implementation,
        reserved
    );
    layout!(
        TypeCodecService,
        TypeCodecService,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        decode,
        encode,
        reserved
    );
    layout!(
        TypeCodecServiceV2,
        TypeCodecServiceV2,
        v1,
        compare,
        comparison_reserved
    );
    layout!(
        TypeComparison,
        TypeComparison,
        struct_size,
        ordering,
        reserved
    );
    for (name, value) in [
        ("kind.type", TYPE as usize),
        ("kind.cast", CAST as usize),
        (
            "cast.explicit",
            seekdb_extension::CastContext::Explicit as usize,
        ),
        (
            "cast.assignment",
            seekdb_extension::CastContext::Assignment as usize,
        ),
        (
            "cast.implicit",
            seekdb_extension::CastContext::Implicit as usize,
        ),
    ] {
        rust.insert(name.to_owned(), value);
    }
    layout!(
        FunctionV2,
        FunctionV2,
        descriptor,
        argument_type_ids,
        argument_type_count,
        signature_flags,
        signature_reserved
    );
    layout!(
        Value,
        Value,
        struct_size,
        type_id,
        data,
        data_size,
        is_null,
        reserved_bytes,
        reserved
    );
    layout!(
        Result,
        Value,
        struct_size,
        type_id,
        data,
        data_size,
        is_null,
        reserved_bytes,
        reserved
    );
    layout!(
        ContextV1,
        ContextV1,
        struct_size,
        host,
        emit_result,
        reserved
    );
    layout!(ContextV2, ContextV2, v1, sql_api, sql_context, reserved);
    layout!(SqlApiV2, SqlApiV2, v1, poll_query, reserved);
    layout!(SqlApiV3, SqlApiV3, v2, lookup_routine, reserved);
    layout!(SqlApiV4, SqlApiV4, v3, mutate_routine, reserved);
    layout!(
        RoutineMutationResult,
        RoutineMutationResult,
        struct_size,
        outcome,
        database_error,
        object_id,
        close_error,
        identity_error,
        data_rollback_error,
        view_rollback_error,
        poison_error,
        reserved
    );
    layout!(
        RoutineLookupResult,
        RoutineLookupResult,
        struct_size,
        reserved_word,
        database_error,
        object_id,
        reserved
    );
    layout!(TableContextV3, TableContextV3, v2, sql_api, reserved);
    layout!(
        TableContextV4,
        TableContextV4,
        v3,
        column_count,
        reserved_word,
        requested_columns,
        reserved
    );
    layout!(
        TableContextV2,
        TableContextV2,
        v1,
        query_context,
        poll_query,
        reserved
    );
    layout!(
        QueryStatus,
        QueryStatus,
        struct_size,
        reserved_word,
        database_error,
        remaining_us,
        reserved
    );
    layout!(ResolvedType, ResolvedType, struct_size, type_id, reserved);
    layout!(
        FunctionServiceV2,
        FunctionServiceV2,
        v1,
        resolve_result,
        resolution_reserved
    );
    rust.insert("resolution.minor".to_owned(), RESULT_TYPE_MINOR as usize);
    rust.insert("resolution.max_identifier".to_owned(), MAX_IDENTIFIER_BYTES);
    layout!(
        BatchRow,
        BatchRow,
        struct_size,
        argument_count,
        arguments,
        reserved
    );
    layout!(
        BatchContext,
        BatchContext,
        struct_size,
        reserved_word,
        query_context,
        host,
        emit_result,
        reserved
    );
    layout!(
        FunctionServiceV3,
        FunctionServiceV3,
        v2,
        execute_batch,
        batch_reserved
    );
    rust.insert("batch.minor".to_owned(), BATCH_MINOR as usize);
    rust.insert("batch.max_rows".to_owned(), MAX_BATCH_ROWS as usize);
    rust.insert("batch.max_bytes".to_owned(), MAX_BATCH_BYTES as usize);
    layout!(
        FunctionService,
        FunctionService,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        execute,
        reserved
    );
    layout!(
        SqlValue,
        SqlValue,
        struct_size,
        kind,
        data,
        data_size,
        reserved
    );
    layout!(
        SqlResult,
        SqlResult,
        struct_size,
        reserved_word,
        database_error,
        affected_rows,
        returned_rows,
        reserved
    );
    layout!(
        SqlApi,
        SqlApi,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        execute,
        reserved
    );
    layout!(
        TableColumn,
        TableColumn,
        struct_size,
        sql_name,
        type_id,
        nullable,
        reserved_bytes,
        reserved
    );
    layout!(
        TableFunction,
        TableFunction,
        struct_size,
        object_id,
        sql_name,
        minimum_arity,
        maximum_arity,
        argument_type_ids,
        argument_type_count,
        signature_flags,
        columns,
        column_count,
        reserved_word,
        flags,
        implementation,
        reserved
    );
    layout!(
        TableRow,
        TableRow,
        struct_size,
        columns,
        column_count,
        reserved_word,
        reserved
    );
    layout!(
        TableContext,
        TableContext,
        struct_size,
        host,
        emit_row,
        reserved
    );
    layout!(
        TableFunctionService,
        TableFunctionService,
        struct_size,
        spi_major,
        spi_minor,
        reserved_word,
        open,
        next,
        rescan,
        close,
        reserved
    );
    layout!(
        TablePlanningInfo,
        TablePlanningInfo,
        struct_size,
        argument_count,
        object_id,
        argument_type_ids,
        column_count,
        reserved_word,
        reserved
    );
    layout!(
        TableEstimate,
        TableEstimate,
        struct_size,
        reserved_word,
        rows,
        row_width,
        total_cost,
        reserved
    );
    layout!(
        TableFunctionServiceV2,
        TableFunctionServiceV2,
        v1,
        estimate,
        reserved
    );
    rust.insert("kind.table".into(), TABLE_FUNCTION as usize);
    rust.insert("status.end".into(), END_OF_STREAM as usize);
    assert_eq!(c, rust);
}
