/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * C ABI for the Rust crate `sql-nio` — the reactor that replaces seekdb's
 * C++ ObSqlNioImpl. C++ calls into the reactor through the `nio_*` functions;
 * the reactor calls back into C++ through the `ob_sql_sock_handler_on_*`
 * functions declared below, which the C++ side defines.
 *
 * Generated by cbindgen from the crate's ABI items. DO NOT EDIT: change the
 * Rust side instead, then rebuild.
 */

#ifndef NIO_H
#define NIO_H

#include <stddef.h>
#include <stdint.h>

#define NIO_PACKET_LOGIN 1

#define NIO_PACKET_COMMAND 2

#define NIO_PACKET_AUTH_SWITCH_RESPONSE 3

#define NIO_TLS_MIN_NONE 0

#define NIO_TLS_MIN_TLSV1 1

#define NIO_TLS_MIN_TLSV1_1 2

#define NIO_TLS_MIN_TLSV1_2 3

#define NIO_TLS_MIN_TLSV1_3 4

#define NIO_MYSQL_COMMAND_LAYOUT_BYTES 1

#define NIO_MYSQL_COMMAND_LAYOUT_FIELD_LIST 2

#define NIO_MYSQL_COMMAND_LAYOUT_U32 3

#define NIO_MYSQL_COMMAND_LAYOUT_U16 4

#define NIO_MYSQL_COMMAND_LAYOUT_FETCH 5

#define NIO_MYSQL_COMMAND_LAYOUT_LONG_DATA 6

#define NIO_MYSQL_COMMAND_LAYOUT_CHANGE_USER 7

#define NIO_MYSQL_COMMAND_LAYOUT_EXECUTE 8

#define NIO_MYSQL_COMMAND_LAYOUT_EMPTY 9

#define NIO_MYSQL_COMMAND_LAYOUT_U8 10

#define NIO_MYSQL_CHANGE_USER_HAS_CHARSET (1 << 0)

#define NIO_MYSQL_CHANGE_USER_HAS_PLUGIN (1 << 1)

#define NIO_MYSQL_CHANGE_USER_HAS_ATTRS (1 << 2)

#define NIO_MYSQL_CHANGE_USER_SECURE_AUTH (1 << 3)

#define NIO_MYSQL_OK_USE_STANDARD_SERIALIZE (1 << 0)

#define NIO_MYSQL_OK_SCHEMA_CHANGED (1 << 1)

#define NIO_MYSQL_OK_STATE_CHANGED (1 << 2)

#define NIO_MYSQL_ROW_TEXT 0

#define NIO_MYSQL_ROW_BINARY 1

#define NIO_MYSQL_CELL_NULL 0

#define NIO_MYSQL_CELL_LENENC_BYTES 1

#define NIO_MYSQL_CELL_I8 2

#define NIO_MYSQL_CELL_I16 3

#define NIO_MYSQL_CELL_I32 4

#define NIO_MYSQL_CELL_I64 5

#define NIO_MYSQL_CELL_F32_BITS 6

#define NIO_MYSQL_CELL_F64_BITS 7

#define NIO_MYSQL_CELL_YEAR 8

#define NIO_MYSQL_CELL_DATE 9

#define NIO_MYSQL_CELL_DATETIME 10

#define NIO_MYSQL_CELL_TIME 11

#define NIO_MYSQL_CELL_BIT 12

#define NIO_MYSQL_CELL_LEGACY_LENENC_NULL 13

#define NIO_MYSQL_CELL_TIME_NEGATIVE (1 << 0)

#define NIO_START_OK 0

#define NIO_START_EINVAL 1

#define NIO_START_EADDR 3

#define NIO_START_ECALLBACKS 4

#define NIO_START_EIO 5

#define NIO_START_ETLS 6

#define NIO_AUTH_NO_CHANGE 0

#define NIO_AUTH_OK 1

#define NIO_AUTH_SWITCH_SENT 2

#define NIO_FRAME_ERROR -1

#define NIO_FRAME_OK 0

#define NIO_FRAME_NEED_MORE 1

#define NIO_MYSQL_EXECUTE_PARSE_OK 0

#define NIO_MYSQL_EXECUTE_PARSE_INVALID_ARGUMENT -1

#define NIO_MYSQL_EXECUTE_PARSE_MALFORMED -2

#define NIO_MYSQL_EXECUTE_PARSE_UNSUPPORTED -3

#define NIO_MYSQL_EXECUTE_PARSE_CAPACITY -4

#define NIO_MYSQL_EXECUTE_VALUE_NULL 1

#define NIO_MYSQL_EXECUTE_VALUE_I64 2

#define NIO_MYSQL_EXECUTE_VALUE_U64 3

#define NIO_MYSQL_EXECUTE_VALUE_F32_BITS 4

#define NIO_MYSQL_EXECUTE_VALUE_F64_BITS 5

#define NIO_MYSQL_EXECUTE_VALUE_BYTES 6

#define NIO_MYSQL_EXECUTE_VALUE_YEAR 7

#define NIO_MYSQL_EXECUTE_VALUE_DATE 8

#define NIO_MYSQL_EXECUTE_VALUE_DATETIME 9

#define NIO_MYSQL_EXECUTE_VALUE_TIMESTAMP 10

#define NIO_MYSQL_EXECUTE_VALUE_TIME 11

#define NIO_MYSQL_EXECUTE_VALUE_LONG_DATA 12

#define NIO_MYSQL_EXECUTE_PARAM_UNSIGNED (1 << 0)

#define NIO_MYSQL_EXECUTE_PARAM_NEGATIVE (1 << 1)

typedef struct NioConnectionHandle NioConnectionHandle;

typedef struct NioReactor NioReactor;

typedef struct NioGreetingInfo {
  uint32_t sessid;
  uint8_t scramble[20];
  uint8_t version[64];
  int64_t version_len;
  uint16_t status_flags;
  uint8_t reserved[6];
} NioGreetingInfo;

typedef struct NioMysqlCommandField {
  int32_t off;
  int32_t len;
} NioMysqlCommandField;

typedef struct NioMysqlCommandView {
  uint32_t command;
  uint32_t layout;
  int64_t scalar0;
  int64_t scalar1;
  struct NioMysqlCommandField fields[4];
  int64_t scalar2;
} NioMysqlCommandView;

typedef struct NioLoginField {
  int32_t off;
  int32_t len;
} NioLoginField;

typedef struct NioLoginAttr {
  int32_t key_off;
  int32_t key_len;
  int32_t value_off;
  int32_t value_len;
} NioLoginAttr;

typedef struct NioLoginView {
  uint32_t capabilities;
  uint8_t charset;
  uint8_t reserved[3];
  struct NioLoginField username;
  struct NioLoginField auth_response;
  struct NioLoginField database;
  struct NioLoginField auth_plugin_name;
  int32_t attr_count;
  const struct NioLoginAttr *attrs;
} NioLoginView;

typedef struct NioTlsStringView {
  const char *data;
  int64_t len;
} NioTlsStringView;

typedef struct NioTlsSessionInfo {
  uint8_t tls_active;
  uint8_t peer_cert_present;
  uint8_t peer_cert_verified;
  uint8_t peer_cert_info_valid;
  uint8_t reserved[4];
  struct NioTlsStringView cipher_name;
  struct NioTlsStringView peer_cert_common_name;
  struct NioTlsStringView peer_cert_issuer;
  struct NioTlsStringView peer_cert_subject;
} NioTlsSessionInfo;

typedef struct NioTlsConfig {
  const char *ca_file;
  const char *cert_file;
  const char *key_file;
  uint8_t min_tls_version;
  uint8_t reserved[7];
} NioTlsConfig;

typedef struct NioByteView {
  const char *data;
  int64_t len;
} NioByteView;

typedef struct NioMysqlFieldView {
  struct NioByteView schema;
  struct NioByteView table;
  struct NioByteView org_table;
  struct NioByteView name;
  struct NioByteView org_name;
  struct NioByteView type_owner;
  struct NioByteView type_name;
  uint32_t column_length;
  uint16_t charset;
  uint16_t flags;
  uint32_t field_type;
  uint32_t default_type;
  uint8_t decimals;
  uint8_t reserved[7];
} NioMysqlFieldView;

typedef struct NioMysqlKvView {
  struct NioByteView key;
  struct NioByteView value;
} NioMysqlKvView;

typedef struct NioMysqlOkView {
  uint64_t affected_rows;
  uint64_t last_insert_id;
  uint32_t capability_flags;
  uint32_t behavior_flags;
  uint16_t status_flags;
  uint16_t warnings;
  uint32_t reserved;
  struct NioByteView message;
  struct NioByteView changed_schema;
  const struct NioMysqlKvView *system_vars;
  int64_t system_var_count;
  const struct NioMysqlKvView *user_vars;
  int64_t user_var_count;
} NioMysqlOkView;

typedef struct NioMysqlCellView {
  struct NioByteView bytes;
  uint64_t value;
  uint32_t days;
  uint32_t microseconds;
  uint16_t year;
  uint8_t month;
  uint8_t day;
  uint8_t hour;
  uint8_t minute;
  uint8_t second;
  uint8_t kind;
  uint8_t flags;
  uint8_t bit_len;
  uint8_t reserved[6];
} NioMysqlCellView;

typedef struct NioMysqlRowView {
  const struct NioMysqlCellView *cells;
  int64_t cell_count;
  uint32_t protocol;
  uint32_t reserved;
} NioMysqlRowView;

typedef struct NioMysqlExecuteParamMeta {
  uint16_t mysql_type;
  uint8_t type_flags;
  uint8_t reserved;
} NioMysqlExecuteParamMeta;

typedef struct NioMysqlExecuteParam {
  uint64_t value;
  int32_t value_off;
  int32_t value_len;
  uint32_t days;
  uint32_t microseconds;
  uint16_t year;
  uint16_t mysql_type;
  uint8_t type_flags;
  uint8_t kind;
  uint8_t flags;
  uint8_t month;
  uint8_t day;
  uint8_t hour;
  uint8_t minute;
  uint8_t second;
  uint8_t reserved[4];
} NioMysqlExecuteParam;

typedef struct NioMysqlExecuteParseResult {
  uint8_t new_params_bound_flag;
  uint8_t reserved[7];
} NioMysqlExecuteParseResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int nio_set_shutdown(void *sess, uint64_t generation);

void nio_shutdown(void *sess);

void nio_bind_sql_session(void *sess);

int nio_release_sql_session(void *sess);

extern int ob_sql_sock_handler_on_connect(void *handler,
                                          void *sess,
                                          int fd,
                                          int is_unix,
                                          struct NioGreetingInfo *greeting);

extern int ob_sql_sock_handler_on_readable(void *handler,
                                           void *sess,
                                           char *body,
                                           int64_t body_len,
                                           uint64_t wire_bytes,
                                           int packet_kind,
                                           const struct NioMysqlCommandView *command_view,
                                           uint64_t generation);

extern void ob_sql_sock_handler_on_disconnect(void *handler, void *sess);

extern void ob_sql_sock_handler_on_close(void *handler, void *sess, int err);

int nio_get_login_view(void *sess, uint64_t generation, struct NioLoginView *out);

int nio_get_tls_session_info(void *sess, uint64_t generation, struct NioTlsSessionInfo *out);

struct NioReactor *nio_start(const char *addr,
                             void *handler,
                             size_t session_size,
                             size_t thread_count,
                             const struct NioTlsConfig *tls,
                             size_t tls_size,
                             int32_t *out_err,
                             int disable_tcp);

uint32_t nio_get_bound_tcp_port(const struct NioReactor *reactor);

int nio_update_tcp_keepalive_params(struct NioReactor *reactor,
                                    int enabled,
                                    uint32_t idle,
                                    uint32_t interval,
                                    uint32_t count);

void nio_stop(struct NioReactor *reactor);

void nio_wait_destroy(struct NioReactor *reactor);

struct NioConnectionHandle *nio_connection_handle_acquire(void *sess);

void nio_connection_handle_release(struct NioConnectionHandle *connection_handle);

int nio_wait_one_packet(void *sess,
                        uint64_t generation,
                        int64_t timeout_us,
                        char **body,
                        int64_t *body_len,
                        uint64_t *packet_lease);

int nio_interrupt_read(void *sess, uint64_t generation);

int nio_release_read_packet(void *sess, uint64_t generation, uint64_t packet_lease);

int nio_prepare_commit(struct NioConnectionHandle *connection_handle,
                       uint64_t generation,
                       int auth_outcome);

void nio_commit_request(struct NioConnectionHandle *connection_handle, uint64_t generation);

int nio_response_append_resultset_metadata(struct NioConnectionHandle *connection_handle,
                                           uint64_t generation,
                                           int include_result_header,
                                           const struct NioMysqlFieldView *fields,
                                           int64_t field_count,
                                           uint8_t eof_field_count,
                                           uint16_t warnings,
                                           uint16_t status_flags,
                                           int64_t *packet_count,
                                           int64_t *framed_len);

int nio_response_append_result_header(struct NioConnectionHandle *connection_handle,
                                      uint64_t generation,
                                      uint64_t field_count,
                                      int64_t *framed_len);

int nio_response_append_eof(struct NioConnectionHandle *connection_handle,
                            uint64_t generation,
                            uint8_t field_count,
                            uint16_t warnings,
                            uint16_t status_flags,
                            int64_t *framed_len);

int nio_response_append_prepare_ok(struct NioConnectionHandle *connection_handle,
                                   uint64_t generation,
                                   uint32_t statement_id,
                                   uint16_t column_count,
                                   uint16_t parameter_count,
                                   uint16_t warnings,
                                   int64_t *framed_len);

int nio_response_append_error(struct NioConnectionHandle *connection_handle,
                              uint64_t generation,
                              uint16_t error_code,
                              const char *sql_state,
                              int64_t sql_state_len,
                              const char *message,
                              int64_t message_len,
                              int64_t *framed_len);

int nio_response_append_auth_switch(struct NioConnectionHandle *connection_handle,
                                    uint64_t generation,
                                    const char *plugin_name,
                                    int64_t plugin_name_len,
                                    const char *scramble,
                                    int64_t scramble_len,
                                    int64_t *framed_len);

int nio_response_append_local_infile(struct NioConnectionHandle *connection_handle,
                                     uint64_t generation,
                                     const char *filename,
                                     int64_t filename_len,
                                     int64_t *framed_len);

int nio_response_append_string(struct NioConnectionHandle *connection_handle,
                               uint64_t generation,
                               const char *value,
                               int64_t value_len,
                               int64_t *framed_len);

int nio_response_append_ok(struct NioConnectionHandle *connection_handle,
                           uint64_t generation,
                           const struct NioMysqlOkView *ok_view,
                           int64_t *framed_len);

int nio_response_append_field(struct NioConnectionHandle *connection_handle,
                              uint64_t generation,
                              const struct NioMysqlFieldView *field_view,
                              int64_t *framed_len);

int nio_response_append_row(struct NioConnectionHandle *connection_handle,
                            uint64_t generation,
                            const struct NioMysqlRowView *row_view,
                            int64_t *framed_len);

int nio_response_append_packed_row_blob(struct NioConnectionHandle *connection_handle,
                                        uint64_t generation,
                                        const char *blob,
                                        int64_t blob_len,
                                        int64_t *framed_len);

int nio_response_flush(struct NioConnectionHandle *connection_handle,
                       uint64_t generation,
                       int is_final);

int nio_encode_mysql_packed_row_blob(char *buffer,
                                     int64_t buffer_len,
                                     const struct NioMysqlRowView *row_view,
                                     int64_t *blob_len);

int nio_parse_mysql_execute_params(const char *tail,
                                   int64_t tail_len,
                                   int64_t param_count,
                                   const struct NioMysqlExecuteParamMeta *cached_meta,
                                   int64_t cached_count,
                                   const uint8_t *long_data,
                                   int64_t long_data_count,
                                   struct NioMysqlExecuteParam *out_params,
                                   int64_t out_capacity,
                                   struct NioMysqlExecuteParseResult *out_result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NIO_H */
