/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifdef OB_SYS_PRIV_TYPE_DEF
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_NONE, "")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_SESSION, "CREATE SESSION")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_EXEMPT_RED_PLY, "EXEMPT REDACTION POLICY")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SYSDBA, "SYSDBA")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SYSOPER, "SYSOPER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SYSBACKUP, "SYSBACKUP")

/* table */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_TABLE, "CREATE TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_TABLE, "CREATE ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_TABLE, "ALTER ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_BACKUP_ANY_TABLE, "BACKUP ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_TABLE, "DROP ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_LOCK_ANY_TABLE, "LOCK ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_COMMENT_ANY_TABLE, "COMMENT ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SELECT_ANY_TABLE, "SELECT ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_INSERT_ANY_TABLE, "INSERT ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_UPDATE_ANY_TABLE, "UPDATE ANY TABLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DELETE_ANY_TABLE, "DELETE ANY TABLE")

/* role */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ROLE, "CREATE ROLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_ROLE, "DROP ANY ROLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_GRANT_ANY_ROLE, "GRANT ANY ROLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_ROLE, "ALTER ANY ROLE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_AUDIT_ANY, "AUDIT ANY")

/* privs */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_GRANT_ANY_PRIV, "GRANT ANY PRIVILEGE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_GRANT_ANY_OBJECT_PRIV, "GRANT ANY OBJECT PRIVILEGE")

/* index */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_INDEX, "CREATE ANY INDEX")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_INDEX, "ALTER ANY INDEX")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_INDEX, "DROP ANY INDEX")

/* view */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_VIEW, "CREATE ANY VIEW")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_VIEW, "DROP ANY VIEW")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_VIEW, "CREATE VIEW")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SELECT_ANY_DICTIONARY, "SELECT ANY DICTIONARY")

/* procedure */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_PROC, "CREATE PROCEDURE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_PROC, "CREATE ANY PROCEDURE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_PROC, "ALTER ANY PROCEDURE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_PROC, "DROP ANY PROCEDURE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_EXEC_ANY_PROC, "EXECUTE ANY PROCEDURE")

/* synonym*/
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_SYN, "CREATE SYNONYM")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_SYN, "CREATE ANY SYNONYM")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_SYN, "DROP ANY SYNONYM")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_PUB_SYN, "CREATE PUBLIC SYNONYM")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_PUB_SYN, "DROP PUBLIC SYNONYM")

/* trigger */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_TRIG, "CREATE TRIGGER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_TRIG, "CREATE ANY TRIGGER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_TRIG, "ALTER ANY TRIGGER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_TRIG, "DROP ANY TRIGGER")

/* profile */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_PROFILE, "CREATE PROFILE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_PROFILE, "ALTER PROFILE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_PROFILE, "DROP PROFILE")

/* user*/
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_USER, "CREATE USER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_BECOME_USER, "BECOME USER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_USER, "ALTER USER")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_USER, "DROP USER")

/* type */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_TYPE, "CREATE TYPE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_TYPE, "CREATE ANY TYPE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_TYPE, "ALTER ANY TYPE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_TYPE, "DROP ANY TYPE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_EXEC_ANY_TYPE, "EXECUTE ANY TYPE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_UNDER_ANY_TYPE, "UNDER ANY TYPE")

/* RECYCLEBIN */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_PURGE_DBA_RECYCLEBIN, "PURGE DBA_RECYCLEBIN")

/* outline */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_OUTLINE, "CREATE ANY OUTLINE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_ANY_OUTLINE, "ALTER ANY OUTLINE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_OUTLINE, "DROP ANY OUTLINE")

/* syskm */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SYSKM, "SYSKM")

/* tablespace */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_TABLESPACE, "CREATE TABLESPACE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_TABLESPACE, "ALTER TABLESPACE")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_TABLESPACE, "DROP TABLESPACE")

OB_SYS_PRIV_TYPE_DEF(PRIV_ID_SHOW_PROCESS, "SHOW PROCESS")

OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_SYSTEM, "ALTER SYSTEM")

OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_SESSION, "ALTER SESSION")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_ALTER_DATABASE, "ALTER DATABASE")

/* context */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_CREATE_ANY_CONTEXT, "CREATE ANY CONTEXT")
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_DROP_ANY_CONTEXT, "DROP ANY CONTEXT")

/* vpd */
OB_SYS_PRIV_TYPE_DEF(PRIV_ID_EXEMPT_ACCESS_POLICY, "EXEMPT ACCESS POLICY")

OB_SYS_PRIV_TYPE_DEF(PRIV_ID_MAX, "")
#endif


#ifndef OCEANBASE_SHARE_SCHEMA_OB_SYS_PRIV_TYPE_
#define OCEANBASE_SHARE_SCHEMA_OB_SYS_PRIV_TYPE_

enum OB_RAW_SYS_PRIV_ID 
{
#define OB_SYS_PRIV_TYPE_DEF(priv_id, priv_name) priv_id,
#include "share/schema/ob_sys_priv_type.h"
#undef OB_SYS_PRIV_TYPE_DEF

};

#endif /* OB_SYS_PRIV_TYPE_ */
