"""C++ helpers for seekdb's Bazel build."""

load(
    "@rules_cc//cc:cc_library.bzl",
    _rules_cc_library = "cc_library",
)
load(
    "//bazel:seekdb_build_config.bzl",
    "SEEKDB_C_MODULE_COPTS",
    "SEEKDB_RELEASE_LOCAL_DEFINES",
    "SEEKDB_SEMANTIC_MODULE_COPTS",
    "seekdb_arch_copts",
    "seekdb_platform_local_defines",
    "seekdb_sanity_compiler_inputs",
    "seekdb_sanity_copts",
    "seekdb_sanity_cxxopts",
    "seekdb_sanity_implementation_deps",
    "seekdb_sanity_local_defines",
)
load("//bazel:oblib_compile_deps.bzl", "oblib_compile_deps")

SeekdbUnitySourcesInfo = provider(
    doc = "Original checked-in sources included by one generated Unity source.",
    fields = ["owners"],
)

SeekdbSourceOwnershipInfo = provider(
    doc = "Transitive original-source owners collected by the ownership aspect.",
    fields = ["owners"],
)

def seekdb_cc_library(
        name,
        copts = None,
        local_defines = None,
        sanity_instrumentation = True,
        **kwargs):
    """Defines a first-party library with seekdb's standard compile contract.

    Callers only spell copts/local_defines when a target intentionally differs
    from the normal semantic-module release build.
    """

    additional_compiler_inputs = kwargs.pop("additional_compiler_inputs", [])
    cxxopts = kwargs.pop("cxxopts", [])
    implementation_deps = kwargs.pop("implementation_deps", [])
    public_deps = kwargs.get("deps", [])
    if type(implementation_deps) == "list":
        automatic_oblib_deps = [
            dependency
            for dependency in oblib_compile_deps(name)
            if dependency not in public_deps and dependency not in implementation_deps
        ]
    else:
        automatic_oblib_deps = [
            dependency
            for dependency in oblib_compile_deps(name)
            if dependency not in public_deps
        ]

    _rules_cc_library(
        name = name,
        additional_compiler_inputs = (
            additional_compiler_inputs +
            seekdb_sanity_compiler_inputs(sanity_instrumentation)
        ),
        copts = (
            (SEEKDB_SEMANTIC_MODULE_COPTS if copts == None else copts) +
            seekdb_arch_copts() +
            seekdb_sanity_copts(sanity_instrumentation)
        ),
        cxxopts = cxxopts + seekdb_sanity_cxxopts(sanity_instrumentation),
        implementation_deps = (
            implementation_deps +
            automatic_oblib_deps +
            seekdb_sanity_implementation_deps()
        ),
        linkstatic = True,
        local_defines = (
            (SEEKDB_RELEASE_LOCAL_DEFINES if local_defines == None else local_defines) +
            seekdb_platform_local_defines() +
            seekdb_sanity_local_defines()
        ),
        **kwargs
    )

def _dedupe(values):
    seen = {}
    result = []
    for value in values:
        if value not in seen:
            seen[value] = True
            result.append(value)
    return result

def _package_relative_source(owner_package, source):
    prefix = owner_package + "/"
    if not source.startswith(prefix):
        fail(
            "source %s is outside owner package %s; give it a native Bazel target first" %
            (source, owner_package),
        )
    return source[len(prefix):]


def _emit_unity_source_impl(ctx):
    lines = [
        "/* generated by Bazel; do not edit */",
        "",
    ]
    owners = []
    for target in ctx.attr.srcs:
        files = target[DefaultInfo].files.to_list()
        if len(files) != 1:
            fail(
                "Each Unity member label must provide exactly one file, got %s from %s" %
                (len(files), target.label),
            )
        src = files[0]
        if src.short_path.startswith("../"):
            fail("Unity members must belong to the main seekdb workspace: %s" % src)
        owners.append(src.short_path + "\t" + str(ctx.label))
        lines.append('#include "%s"' % src.short_path)
        lines.append("")
        lines.extend([
            "#ifdef USING_LOG_PREFIX",
            "#undef USING_LOG_PREFIX",
            "#endif",
            "",
        ])

    ctx.actions.write(
        output = ctx.outputs.out,
        content = "\n".join(lines),
    )
    return [
        DefaultInfo(files = depset([ctx.outputs.out])),
        SeekdbUnitySourcesInfo(owners = depset(owners)),
    ]

_emit_unity_source = rule(
    implementation = _emit_unity_source_impl,
    attrs = {
        "out": attr.output(mandatory = True),
        "srcs": attr.label_list(
            allow_files = [".c", ".cc", ".cpp", ".cxx"],
            mandatory = True,
        ),
    },
)

def _source_ownership_aspect_impl(target, ctx):
    transitive = []
    if SeekdbUnitySourcesInfo in target:
        transitive.append(target[SeekdbUnitySourcesInfo].owners)

    if ctx.rule:
        for attr_name in dir(ctx.rule.attr):
            value = getattr(ctx.rule.attr, attr_name)
            if type(value) == "Target":
                if SeekdbSourceOwnershipInfo in value:
                    transitive.append(value[SeekdbSourceOwnershipInfo].owners)
            elif type(value) == "list":
                for dependency in value:
                    if (
                        type(dependency) == "Target" and
                        SeekdbSourceOwnershipInfo in dependency
                    ):
                        transitive.append(
                            dependency[SeekdbSourceOwnershipInfo].owners,
                        )

    return [
        SeekdbSourceOwnershipInfo(
            owners = depset(transitive = transitive),
        ),
    ]

_source_ownership_aspect = aspect(
    implementation = _source_ownership_aspect_impl,
    attr_aspects = ["*"],
)

def _source_ownership_check_impl(ctx):
    owners_by_source = {}
    for entry in ctx.attr.root[SeekdbSourceOwnershipInfo].owners.to_list():
        source, owner = entry.split("\t", 1)
        owners_by_source.setdefault(source, {})[owner] = True

    duplicates = []
    for source, owners in owners_by_source.items():
        if len(owners) > 1:
            duplicates.append(
                "%s -> %s" % (source, ", ".join(sorted(owners))),
            )
    if duplicates:
        fail(
            "production sources have multiple Unity owners:\n  %s" %
            "\n  ".join(sorted(duplicates)),
        )

    output = ctx.actions.declare_file(ctx.label.name + ".ok")
    ctx.actions.write(
        output = output,
        content = "%d uniquely owned Unity sources\n" % len(owners_by_source),
    )
    return [DefaultInfo(files = depset([output]))]

seekdb_source_ownership_check = rule(
    implementation = _source_ownership_check_impl,
    attrs = {
        "root": attr.label(
            mandatory = True,
            aspects = [_source_ownership_aspect],
        ),
    },
)

def seekdb_generated_unity_source(
        name,
        unity_members,
        language = "c++",
        tags = []):
    """Generates one ordered Unity source and returns its target label."""

    if language not in ("c", "c++"):
        fail("language must be 'c' or 'c++', got %s" % language)

    unity_source_target = "_" + name + "_generated_unity"
    _emit_unity_source(
        name = unity_source_target,
        srcs = unity_members,
        out = name + (".unity.c" if language == "c" else ".unity.cpp"),
        tags = tags,
        visibility = ["//visibility:private"],
    )

    return ":" + unity_source_target

def seekdb_unity_cc_library(
        name,
        unity_src,
        unity_members,
        public_hdrs = [],
        private_hdrs = [],
        deps = [],
        implementation_deps = [],
        copts = None,
        local_defines = None,
        sanity_instrumentation = True,
        features = [],
        tags = [],
        visibility = None):
    """Defines a Unity-only C++ library with one Unity translation unit."""

    seekdb_multi_unity_cc_library(
        name = name,
        unity_srcs = [unity_src],
        unity_members = unity_members,
        public_hdrs = public_hdrs,
        private_hdrs = private_hdrs,
        deps = deps,
        implementation_deps = implementation_deps,
        copts = copts,
        local_defines = local_defines,
        sanity_instrumentation = sanity_instrumentation,
        features = features,
        tags = tags,
        visibility = visibility,
    )

def seekdb_multi_unity_cc_library(
        name,
        unity_srcs,
        unity_members,
        public_hdrs = [],
        private_hdrs = [],
        deps = [],
        implementation_deps = [],
        copts = None,
        local_defines = None,
        sanity_instrumentation = True,
        features = [],
        tags = [],
        visibility = None):
    """Defines one C++ library containing multiple Unity translation units.

    Unity members live in a private textual dependency: the Unity source may
    include them, but they are not propagated as part of the module interface.
    """

    if not unity_srcs:
        fail("%s must contain at least one Unity source" % name)

    unity_members_target = "_" + name + "_unity_members"
    seekdb_cc_library(
        name = unity_members_target,
        textual_hdrs = unity_members,
        sanity_instrumentation = sanity_instrumentation,
        tags = tags,
        visibility = ["//visibility:private"],
    )

    seekdb_cc_library(
        name = name,
        srcs = _dedupe(unity_srcs + private_hdrs),
        hdrs = public_hdrs,
        deps = deps,
        implementation_deps = _dedupe(
            [":" + unity_members_target] +
            implementation_deps,
        ),
        copts = copts,
        local_defines = local_defines,
        sanity_instrumentation = sanity_instrumentation,
        features = features,
        tags = tags,
        visibility = visibility,
    )

def seekdb_generated_unity_cc_library(
        name,
        unity_members,
        public_hdrs = [],
        private_hdrs = [],
        deps = [],
        implementation_deps = [],
        copts = None,
        local_defines = None,
        sanity_instrumentation = True,
        language = "c++",
        features = [],
        tags = [],
        visibility = None):
    """Defines a Unity-only library and generates its aggregate source.

    The member order is significant and is preserved. Each include is followed
    by the USING_LOG_PREFIX cleanup required between aggregate members.
    """

    if language not in ("c", "c++"):
        fail("language must be 'c' or 'c++', got %s" % language)

    unity_source = seekdb_generated_unity_source(
        name = name,
        unity_members = unity_members,
        language = language,
        tags = tags,
    )

    seekdb_unity_cc_library(
        name = name,
        unity_src = unity_source,
        unity_members = unity_members,
        public_hdrs = public_hdrs,
        private_hdrs = private_hdrs,
        deps = deps,
        implementation_deps = implementation_deps,
        copts = SEEKDB_C_MODULE_COPTS if language == "c" and copts == None else copts,
        local_defines = local_defines,
        sanity_instrumentation = sanity_instrumentation,
        features = features,
        tags = tags,
        visibility = visibility,
    )

def seekdb_semantic_unity_cc_library(
        name,
        owner_package,
        unity_groups,
        language = "c++",
        expected_group_names = [],
        group_implementation_deps = {},
        source_replacements = {},
        public_hdrs = [],
        private_hdrs = [],
        deps = [],
        implementation_deps = [],
        copts = None,
        local_defines = None,
        sanity_instrumentation = True,
        features = [],
        tags = [],
        visibility = None):
    """Defines one native semantic library from same-language Unity groups.

    By default all generated Unity sources are compiled by one cc_library and
    therefore share one dependency closure.  When group_implementation_deps is
    present, each semantic Unity group is compiled by its own private
    cc_library with the common implementation_deps plus the dependencies
    declared for that group.  The public target remains one linkable module
    whose linking context contains every private group archive.
    """

    if language not in ("c", "c++"):
        fail("language must be 'c' or 'c++', got %s" % language)

    unity_srcs = []
    unity_members = []
    unity_definitions = []
    seen_group_names = {}
    used_replacements = {}
    for group in unity_groups:
        if group.name in seen_group_names:
            fail("%s contains duplicate Unity group %s" % (name, group.name))
        seen_group_names[group.name] = True
        if group.language != language:
            fail("%s expects %s Unity groups, got %s" % (name, language, group.language))
        if group.generated_srcs:
            fail("%s still contains generated sources: %s" % (group.name, group.generated_srcs))
        if group.external_srcs:
            fail("%s still contains external sources: %s" % (group.name, group.external_srcs))

        members = []
        for source in group.srcs:
            if source in source_replacements:
                members.append(source_replacements[source])
                used_replacements[source] = True
            else:
                members.append(_package_relative_source(owner_package, source))
        if not members:
            fail("%s contains an empty Unity group: %s" % (name, group.name))
        unity_members.extend(members)
        unity_src = seekdb_generated_unity_source(
            name = name + "_" + group.name,
            unity_members = members,
            language = language,
            tags = tags,
        )
        unity_srcs.append(unity_src)
        unity_definitions.append(struct(
            group_name = group.name,
            members = members,
            unity_src = unity_src,
        ))

    if not unity_srcs:
        fail("%s has no Unity groups" % name)
    if expected_group_names and sorted(seen_group_names) != sorted(expected_group_names):
        fail(
            "%s Unity groups differ from inventory: expected %s, got %s" %
            (name, sorted(expected_group_names), sorted(seen_group_names)),
        )

    unused_replacements = sorted([
        source
        for source in source_replacements
        if source not in used_replacements
    ])
    if unused_replacements:
        fail("%s has unused source replacements: %s" % (name, unused_replacements))

    if group_implementation_deps:
        unknown_groups = sorted([
            group_name
            for group_name in group_implementation_deps
            if group_name not in seen_group_names
        ])
        missing_groups = sorted([
            group_name
            for group_name in seen_group_names
            if group_name not in group_implementation_deps
        ])
        if unknown_groups or missing_groups:
            fail(
                (
                    "%s group dependency map differs from its Unity groups: " +
                    "unknown=%s missing=%s"
                ) % (name, unknown_groups, missing_groups),
            )
        if public_hdrs or private_hdrs:
            fail(
                "%s partitioned Unity compilation requires headers to have " +
                "separate semantic owner targets" % name,
            )

        group_targets = []
        for definition in unity_definitions:
            group_target = "_" + name + "_" + definition.group_name + "_objects"
            seekdb_unity_cc_library(
                name = group_target,
                unity_src = definition.unity_src,
                unity_members = definition.members,
                deps = deps,
                implementation_deps = (
                    implementation_deps +
                    group_implementation_deps[definition.group_name]
                ),
                copts = SEEKDB_C_MODULE_COPTS if language == "c" and copts == None else copts,
                local_defines = local_defines,
                sanity_instrumentation = sanity_instrumentation,
                features = features,
                tags = tags,
                visibility = ["//visibility:private"],
            )
            group_targets.append(":" + group_target)

        seekdb_cc_library(
            name = name,
            deps = deps,
            implementation_deps = group_targets,
            copts = SEEKDB_C_MODULE_COPTS if language == "c" and copts == None else copts,
            local_defines = local_defines,
            sanity_instrumentation = sanity_instrumentation,
            features = features,
            tags = tags,
            visibility = visibility,
        )
    else:
        seekdb_multi_unity_cc_library(
            name = name,
            unity_srcs = unity_srcs,
            unity_members = unity_members,
            public_hdrs = public_hdrs,
            private_hdrs = private_hdrs,
            deps = deps,
            implementation_deps = implementation_deps,
            copts = SEEKDB_C_MODULE_COPTS if language == "c" and copts == None else copts,
            local_defines = local_defines,
            sanity_instrumentation = sanity_instrumentation,
            features = features,
            tags = tags,
            visibility = visibility,
        )
