/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated by cbindgen from the auto-config crate's C ABI. */

#ifndef SEEKDB_AUTO_CONFIG_H_
#define SEEKDB_AUTO_CONFIG_H_

#include <stdint.h>

typedef struct SeekdbAutoConfigError {
  uint32_t line;
  uint8_t after_replace;
  char message[512];
} SeekdbAutoConfigError;

typedef int (*SeekdbAutoConfigEntryCallback)(void *context,
                                             const char *name,
                                             const char *value,
                                             uint32_t line);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int seekdb_auto_config_supported(const char *path, struct SeekdbAutoConfigError *error);

int seekdb_auto_config_load(const char *path,
                            SeekdbAutoConfigEntryCallback callback,
                            void *context,
                            struct SeekdbAutoConfigError *error);

int seekdb_auto_config_update(const char *path,
                              const char *name,
                              const char *value,
                              uint8_t reset,
                              struct SeekdbAutoConfigError *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SEEKDB_AUTO_CONFIG_H_ */
