/* Copyright (c) 2026 OceanBase. Licensed under the Apache License, Version 2.0. */

#pragma once

/* Generated by cbindgen. Edit src/ffi.rs and rebuild; do not edit this file. */

#include <stddef.h>
#include <stdint.h>

/**
 * Encoding values accepted by both ABI entry points.
 */
#define EMBEDDING_FLOAT 0

#define EMBEDDING_BASE64 1

/**
 * ABI failure categories, independent of server error numbers.
 */
enum EmbeddingStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  EmbeddingStatus_Success,
  EmbeddingStatus_InvalidArgument,
  EmbeddingStatus_AllocationFailed,
  EmbeddingStatus_DimensionMismatch,
  EmbeddingStatus_BufferNotEnough,
  EmbeddingStatus_MissingField,
  EmbeddingStatus_InvalidJson,
  EmbeddingStatus_CallbackFailed,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum EmbeddingStatus EmbeddingStatus;
#else
typedef uint32_t EmbeddingStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Callback errors are returned unchanged in callback_error, only when status
 * is CallbackFailed. All other statuses leave callback_error zero.
 */
typedef struct EmbeddingResult {
  EmbeddingStatus status;
  int32_t callback_error;
} EmbeddingResult;

/**
 * Called only during parse, once per complete vector, until it returns nonzero.
 * The vector is borrowed only during the callback: copy it before returning.
 * Return zero on success or a caller-owned error code to stop parsing.
 */
typedef int32_t (*EmitVector)(void*, const float*, size_t);

/**
 * Borrowed text descriptor; null is permitted only for zero length.
 */
typedef struct EmbeddingBytes {
  const uint8_t *data;
  size_t length;
} EmbeddingBytes;

/**
 * Called once after serialization. The body is borrowed only during the callback;
 * copy it for asynchronous use. Return zero or a caller-owned error code.
 */
typedef int32_t (*EmitBody)(void*, const uint8_t*, size_t);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Parse an embedding response and synchronously emit borrowed vectors.
 *
 * # Safety
 * `data` must identify `length` readable bytes in one allocation, unchanged
 * until return. `emit` and `context` must obey the contract in the C header:
 * the callback must not unwind, retain/free the vector pointer, mutate the input, or
 * release objects still used by this call. The context itself may be null if
 * the callback supports that. Calls sharing mutable state require caller locking.
 */
struct EmbeddingResult embedding_response_parse(const uint8_t *data,
                                                size_t length,
                                                int64_t dimension,
                                                uint32_t encoding,
                                                void *context,
                                                EmitVector emit);

/**
 * Serialize a request and synchronously emit its borrowed body.
 *
 * # Safety
 * The descriptors and their bytes must be readable and unchanged until return.
 * `inputs` must identify `count` aligned descriptors (or null for zero count).
 * The callback must not unwind, retain/free the body pointer, mutate the inputs,
 * or invalidate context. Calls sharing mutable state require locking.
 * Text bytes are preserved with JSON syntax/control bytes escaped. Callers
 * supply UTF-8 text. Nonpositive dimensions are omitted.
 */
struct EmbeddingResult embedding_request_build(const struct EmbeddingBytes *inputs,
                                               size_t count,
                                               struct EmbeddingBytes model,
                                               int64_t dimension,
                                               uint32_t encoding,
                                               void *context,
                                               EmitBody emit);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
