// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: standbyservice.proto

#include "standbyservice.pb.h"
#include "standbyservice.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace standbyservice {

static const char* StandbyService_method_names[] = {
  "/standbyservice.StandbyService/fetch_ls_view",
  "/standbyservice.StandbyService/fetch_tablet_info",
  "/standbyservice.StandbyService/fetch_tablet_sstable_info",
  "/standbyservice.StandbyService/fetch_sstable_macro_info",
  "/standbyservice.StandbyService/fetch_macro_block",
  "/standbyservice.StandbyService/get_ls_view_tablet_count",
  "/standbyservice.StandbyService/check_restore_precondition",
  "/standbyservice.StandbyService/fetch_standby_palf_base_info",
  "/standbyservice.StandbyService/fetch_log",
  "/standbyservice.StandbyService/get_promotion_boundary",
};

std::unique_ptr< StandbyService::Stub> StandbyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StandbyService::Stub> stub(new StandbyService::Stub(channel, options));
  return stub;
}

StandbyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_fetch_ls_view_(StandbyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_fetch_tablet_info_(StandbyService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_fetch_tablet_sstable_info_(StandbyService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_fetch_sstable_macro_info_(StandbyService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_fetch_macro_block_(StandbyService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_get_ls_view_tablet_count_(StandbyService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_check_restore_precondition_(StandbyService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_fetch_standby_palf_base_info_(StandbyService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_fetch_log_(StandbyService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_get_promotion_boundary_(StandbyService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::standbyservice::FetchLSViewRes>* StandbyService::Stub::fetch_ls_viewRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLSViewReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchLSViewRes>::Create(channel_.get(), rpcmethod_fetch_ls_view_, context, request);
}

void StandbyService::Stub::async::fetch_ls_view(::grpc::ClientContext* context, const ::standbyservice::FetchLSViewReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchLSViewRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchLSViewRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_ls_view_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchLSViewRes>* StandbyService::Stub::Asyncfetch_ls_viewRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLSViewReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchLSViewRes>::Create(channel_.get(), cq, rpcmethod_fetch_ls_view_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchLSViewRes>* StandbyService::Stub::PrepareAsyncfetch_ls_viewRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLSViewReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchLSViewRes>::Create(channel_.get(), cq, rpcmethod_fetch_ls_view_, context, request, false, nullptr);
}

::grpc::ClientReader< ::standbyservice::FetchTabletInfoRes>* StandbyService::Stub::fetch_tablet_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletInfoReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchTabletInfoRes>::Create(channel_.get(), rpcmethod_fetch_tablet_info_, context, request);
}

void StandbyService::Stub::async::fetch_tablet_info(::grpc::ClientContext* context, const ::standbyservice::FetchTabletInfoReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchTabletInfoRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchTabletInfoRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_tablet_info_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchTabletInfoRes>* StandbyService::Stub::Asyncfetch_tablet_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletInfoReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchTabletInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_tablet_info_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchTabletInfoRes>* StandbyService::Stub::PrepareAsyncfetch_tablet_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchTabletInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_tablet_info_, context, request, false, nullptr);
}

::grpc::ClientReader< ::standbyservice::FetchTabletSSTableInfoRes>* StandbyService::Stub::fetch_tablet_sstable_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletSSTableInfoReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchTabletSSTableInfoRes>::Create(channel_.get(), rpcmethod_fetch_tablet_sstable_info_, context, request);
}

void StandbyService::Stub::async::fetch_tablet_sstable_info(::grpc::ClientContext* context, const ::standbyservice::FetchTabletSSTableInfoReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchTabletSSTableInfoRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchTabletSSTableInfoRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_tablet_sstable_info_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchTabletSSTableInfoRes>* StandbyService::Stub::Asyncfetch_tablet_sstable_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletSSTableInfoReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchTabletSSTableInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_tablet_sstable_info_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchTabletSSTableInfoRes>* StandbyService::Stub::PrepareAsyncfetch_tablet_sstable_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchTabletSSTableInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchTabletSSTableInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_tablet_sstable_info_, context, request, false, nullptr);
}

::grpc::ClientReader< ::standbyservice::FetchSSTableMacroInfoRes>* StandbyService::Stub::fetch_sstable_macro_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchSSTableMacroInfoReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchSSTableMacroInfoRes>::Create(channel_.get(), rpcmethod_fetch_sstable_macro_info_, context, request);
}

void StandbyService::Stub::async::fetch_sstable_macro_info(::grpc::ClientContext* context, const ::standbyservice::FetchSSTableMacroInfoReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchSSTableMacroInfoRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchSSTableMacroInfoRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_sstable_macro_info_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchSSTableMacroInfoRes>* StandbyService::Stub::Asyncfetch_sstable_macro_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchSSTableMacroInfoReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchSSTableMacroInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_sstable_macro_info_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchSSTableMacroInfoRes>* StandbyService::Stub::PrepareAsyncfetch_sstable_macro_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchSSTableMacroInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchSSTableMacroInfoRes>::Create(channel_.get(), cq, rpcmethod_fetch_sstable_macro_info_, context, request, false, nullptr);
}

::grpc::ClientReader< ::standbyservice::FetchMacroBlockRes>* StandbyService::Stub::fetch_macro_blockRaw(::grpc::ClientContext* context, const ::standbyservice::FetchMacroBlockReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchMacroBlockRes>::Create(channel_.get(), rpcmethod_fetch_macro_block_, context, request);
}

void StandbyService::Stub::async::fetch_macro_block(::grpc::ClientContext* context, const ::standbyservice::FetchMacroBlockReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchMacroBlockRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchMacroBlockRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_macro_block_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchMacroBlockRes>* StandbyService::Stub::Asyncfetch_macro_blockRaw(::grpc::ClientContext* context, const ::standbyservice::FetchMacroBlockReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchMacroBlockRes>::Create(channel_.get(), cq, rpcmethod_fetch_macro_block_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchMacroBlockRes>* StandbyService::Stub::PrepareAsyncfetch_macro_blockRaw(::grpc::ClientContext* context, const ::standbyservice::FetchMacroBlockReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchMacroBlockRes>::Create(channel_.get(), cq, rpcmethod_fetch_macro_block_, context, request, false, nullptr);
}

::grpc::Status StandbyService::Stub::get_ls_view_tablet_count(::grpc::ClientContext* context, const ::standbyservice::GetLSViewTabletCountReq& request, ::standbyservice::GetLSViewTabletCountRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::standbyservice::GetLSViewTabletCountReq, ::standbyservice::GetLSViewTabletCountRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_ls_view_tablet_count_, context, request, response);
}

void StandbyService::Stub::async::get_ls_view_tablet_count(::grpc::ClientContext* context, const ::standbyservice::GetLSViewTabletCountReq* request, ::standbyservice::GetLSViewTabletCountRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::standbyservice::GetLSViewTabletCountReq, ::standbyservice::GetLSViewTabletCountRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_ls_view_tablet_count_, context, request, response, std::move(f));
}

void StandbyService::Stub::async::get_ls_view_tablet_count(::grpc::ClientContext* context, const ::standbyservice::GetLSViewTabletCountReq* request, ::standbyservice::GetLSViewTabletCountRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_ls_view_tablet_count_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::GetLSViewTabletCountRes>* StandbyService::Stub::PrepareAsyncget_ls_view_tablet_countRaw(::grpc::ClientContext* context, const ::standbyservice::GetLSViewTabletCountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::standbyservice::GetLSViewTabletCountRes, ::standbyservice::GetLSViewTabletCountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_ls_view_tablet_count_, context, request);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::GetLSViewTabletCountRes>* StandbyService::Stub::Asyncget_ls_view_tablet_countRaw(::grpc::ClientContext* context, const ::standbyservice::GetLSViewTabletCountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_ls_view_tablet_countRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StandbyService::Stub::check_restore_precondition(::grpc::ClientContext* context, const ::standbyservice::CheckRestorePreconditionReq& request, ::standbyservice::CheckRestorePreconditionRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::standbyservice::CheckRestorePreconditionReq, ::standbyservice::CheckRestorePreconditionRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_check_restore_precondition_, context, request, response);
}

void StandbyService::Stub::async::check_restore_precondition(::grpc::ClientContext* context, const ::standbyservice::CheckRestorePreconditionReq* request, ::standbyservice::CheckRestorePreconditionRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::standbyservice::CheckRestorePreconditionReq, ::standbyservice::CheckRestorePreconditionRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_check_restore_precondition_, context, request, response, std::move(f));
}

void StandbyService::Stub::async::check_restore_precondition(::grpc::ClientContext* context, const ::standbyservice::CheckRestorePreconditionReq* request, ::standbyservice::CheckRestorePreconditionRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_check_restore_precondition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::CheckRestorePreconditionRes>* StandbyService::Stub::PrepareAsynccheck_restore_preconditionRaw(::grpc::ClientContext* context, const ::standbyservice::CheckRestorePreconditionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::standbyservice::CheckRestorePreconditionRes, ::standbyservice::CheckRestorePreconditionReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_check_restore_precondition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::CheckRestorePreconditionRes>* StandbyService::Stub::Asynccheck_restore_preconditionRaw(::grpc::ClientContext* context, const ::standbyservice::CheckRestorePreconditionReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccheck_restore_preconditionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StandbyService::Stub::fetch_standby_palf_base_info(::grpc::ClientContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq& request, ::standbyservice::FetchStandbyPalfBaseInfoRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::standbyservice::FetchStandbyPalfBaseInfoReq, ::standbyservice::FetchStandbyPalfBaseInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_fetch_standby_palf_base_info_, context, request, response);
}

void StandbyService::Stub::async::fetch_standby_palf_base_info(::grpc::ClientContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq* request, ::standbyservice::FetchStandbyPalfBaseInfoRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::standbyservice::FetchStandbyPalfBaseInfoReq, ::standbyservice::FetchStandbyPalfBaseInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_fetch_standby_palf_base_info_, context, request, response, std::move(f));
}

void StandbyService::Stub::async::fetch_standby_palf_base_info(::grpc::ClientContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq* request, ::standbyservice::FetchStandbyPalfBaseInfoRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_fetch_standby_palf_base_info_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::FetchStandbyPalfBaseInfoRes>* StandbyService::Stub::PrepareAsyncfetch_standby_palf_base_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::standbyservice::FetchStandbyPalfBaseInfoRes, ::standbyservice::FetchStandbyPalfBaseInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_fetch_standby_palf_base_info_, context, request);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::FetchStandbyPalfBaseInfoRes>* StandbyService::Stub::Asyncfetch_standby_palf_base_infoRaw(::grpc::ClientContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncfetch_standby_palf_base_infoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::standbyservice::FetchLogRes>* StandbyService::Stub::fetch_logRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLogReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::standbyservice::FetchLogRes>::Create(channel_.get(), rpcmethod_fetch_log_, context, request);
}

void StandbyService::Stub::async::fetch_log(::grpc::ClientContext* context, const ::standbyservice::FetchLogReq* request, ::grpc::ClientReadReactor< ::standbyservice::FetchLogRes>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::standbyservice::FetchLogRes>::Create(stub_->channel_.get(), stub_->rpcmethod_fetch_log_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchLogRes>* StandbyService::Stub::Asyncfetch_logRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLogReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchLogRes>::Create(channel_.get(), cq, rpcmethod_fetch_log_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::standbyservice::FetchLogRes>* StandbyService::Stub::PrepareAsyncfetch_logRaw(::grpc::ClientContext* context, const ::standbyservice::FetchLogReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::standbyservice::FetchLogRes>::Create(channel_.get(), cq, rpcmethod_fetch_log_, context, request, false, nullptr);
}

::grpc::Status StandbyService::Stub::get_promotion_boundary(::grpc::ClientContext* context, const ::standbyservice::GetPromotionBoundaryReq& request, ::standbyservice::GetPromotionBoundaryRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::standbyservice::GetPromotionBoundaryReq, ::standbyservice::GetPromotionBoundaryRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_promotion_boundary_, context, request, response);
}

void StandbyService::Stub::async::get_promotion_boundary(::grpc::ClientContext* context, const ::standbyservice::GetPromotionBoundaryReq* request, ::standbyservice::GetPromotionBoundaryRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::standbyservice::GetPromotionBoundaryReq, ::standbyservice::GetPromotionBoundaryRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_promotion_boundary_, context, request, response, std::move(f));
}

void StandbyService::Stub::async::get_promotion_boundary(::grpc::ClientContext* context, const ::standbyservice::GetPromotionBoundaryReq* request, ::standbyservice::GetPromotionBoundaryRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_promotion_boundary_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::GetPromotionBoundaryRes>* StandbyService::Stub::PrepareAsyncget_promotion_boundaryRaw(::grpc::ClientContext* context, const ::standbyservice::GetPromotionBoundaryReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::standbyservice::GetPromotionBoundaryRes, ::standbyservice::GetPromotionBoundaryReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_promotion_boundary_, context, request);
}

::grpc::ClientAsyncResponseReader< ::standbyservice::GetPromotionBoundaryRes>* StandbyService::Stub::Asyncget_promotion_boundaryRaw(::grpc::ClientContext* context, const ::standbyservice::GetPromotionBoundaryReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_promotion_boundaryRaw(context, request, cq);
  result->StartCall();
  return result;
}

StandbyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchLSViewReq, ::standbyservice::FetchLSViewRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchLSViewReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchLSViewRes>* writer) {
               return service->fetch_ls_view(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchTabletInfoReq, ::standbyservice::FetchTabletInfoRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchTabletInfoReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchTabletInfoRes>* writer) {
               return service->fetch_tablet_info(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchTabletSSTableInfoReq, ::standbyservice::FetchTabletSSTableInfoRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchTabletSSTableInfoReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchTabletSSTableInfoRes>* writer) {
               return service->fetch_tablet_sstable_info(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchSSTableMacroInfoReq, ::standbyservice::FetchSSTableMacroInfoRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchSSTableMacroInfoReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchSSTableMacroInfoRes>* writer) {
               return service->fetch_sstable_macro_info(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[4],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchMacroBlockReq, ::standbyservice::FetchMacroBlockRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchMacroBlockReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchMacroBlockRes>* writer) {
               return service->fetch_macro_block(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StandbyService::Service, ::standbyservice::GetLSViewTabletCountReq, ::standbyservice::GetLSViewTabletCountRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::GetLSViewTabletCountReq* req,
             ::standbyservice::GetLSViewTabletCountRes* resp) {
               return service->get_ls_view_tablet_count(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StandbyService::Service, ::standbyservice::CheckRestorePreconditionReq, ::standbyservice::CheckRestorePreconditionRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::CheckRestorePreconditionReq* req,
             ::standbyservice::CheckRestorePreconditionRes* resp) {
               return service->check_restore_precondition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StandbyService::Service, ::standbyservice::FetchStandbyPalfBaseInfoReq, ::standbyservice::FetchStandbyPalfBaseInfoRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchStandbyPalfBaseInfoReq* req,
             ::standbyservice::FetchStandbyPalfBaseInfoRes* resp) {
               return service->fetch_standby_palf_base_info(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StandbyService::Service, ::standbyservice::FetchLogReq, ::standbyservice::FetchLogRes>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::FetchLogReq* req,
             ::grpc::ServerWriter<::standbyservice::FetchLogRes>* writer) {
               return service->fetch_log(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StandbyService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StandbyService::Service, ::standbyservice::GetPromotionBoundaryReq, ::standbyservice::GetPromotionBoundaryRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StandbyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::standbyservice::GetPromotionBoundaryReq* req,
             ::standbyservice::GetPromotionBoundaryRes* resp) {
               return service->get_promotion_boundary(ctx, req, resp);
             }, this)));
}

StandbyService::Service::~Service() {
}

::grpc::Status StandbyService::Service::fetch_ls_view(::grpc::ServerContext* context, const ::standbyservice::FetchLSViewReq* request, ::grpc::ServerWriter< ::standbyservice::FetchLSViewRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_tablet_info(::grpc::ServerContext* context, const ::standbyservice::FetchTabletInfoReq* request, ::grpc::ServerWriter< ::standbyservice::FetchTabletInfoRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_tablet_sstable_info(::grpc::ServerContext* context, const ::standbyservice::FetchTabletSSTableInfoReq* request, ::grpc::ServerWriter< ::standbyservice::FetchTabletSSTableInfoRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_sstable_macro_info(::grpc::ServerContext* context, const ::standbyservice::FetchSSTableMacroInfoReq* request, ::grpc::ServerWriter< ::standbyservice::FetchSSTableMacroInfoRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_macro_block(::grpc::ServerContext* context, const ::standbyservice::FetchMacroBlockReq* request, ::grpc::ServerWriter< ::standbyservice::FetchMacroBlockRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::get_ls_view_tablet_count(::grpc::ServerContext* context, const ::standbyservice::GetLSViewTabletCountReq* request, ::standbyservice::GetLSViewTabletCountRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::check_restore_precondition(::grpc::ServerContext* context, const ::standbyservice::CheckRestorePreconditionReq* request, ::standbyservice::CheckRestorePreconditionRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_standby_palf_base_info(::grpc::ServerContext* context, const ::standbyservice::FetchStandbyPalfBaseInfoReq* request, ::standbyservice::FetchStandbyPalfBaseInfoRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::fetch_log(::grpc::ServerContext* context, const ::standbyservice::FetchLogReq* request, ::grpc::ServerWriter< ::standbyservice::FetchLogRes>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StandbyService::Service::get_promotion_boundary(::grpc::ServerContext* context, const ::standbyservice::GetPromotionBoundaryReq* request, ::standbyservice::GetPromotionBoundaryRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace standbyservice
