"""Generated source inventory for the native Observer composition root."""

OBSERVER_UNITY_GROUPS = [
    struct(
        name = "ob_server_ai_service_0",
        language = "c++",
        srcs = [
            "src/observer/ai_service/ob_ai_service_proxy.cpp",
            "src/observer/ai_service/ob_ai_service_executor.cpp",
            "src/observer/ob_system_package_load_service.cpp",
            "src/observer/ob_tablet_runtime_meta_updater.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_change_stream_0",
        language = "c++",
        srcs = [
            "src/observer/change_stream/ob_change_stream_fetcher.cpp",
            "src/observer/change_stream/ob_change_stream_dispatcher.cpp",
            "src/observer/change_stream/ob_change_stream_worker.cpp",
            "src/observer/change_stream/ob_change_stream_plugin.cpp",
            "src/observer/change_stream/ob_change_stream_mgr.cpp",
            "src/observer/change_stream/ob_cs_plugin_async_index.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_common_0",
        language = "c++",
        srcs = [
            "src/observer/ob_inner_sql_connection.cpp",
            "src/observer/ob_inner_connection_lock_util.cpp",
            "src/observer/ob_inner_sql_read_context.cpp",
            "src/observer/ob_inner_sql_result.cpp",
            "src/observer/ob_internal_table_refresh_adapter.cpp",
            "src/observer/ob_ls_runtime_adapter.cpp",
            "src/observer/ob_req_time_service.cpp",
            "src/observer/ob_server_reload_config.cpp",
            "src/observer/ob_server_schema_updater.cpp",
            "src/observer/ob_server_utils.cpp",
            "src/observer/ob_signal_handle.cpp",
            "src/observer/ob_srv_deliver.cpp",
            "src/observer/ob_srv_network_frame.cpp",
            "src/observer/ob_srv_xlator.cpp",
            "src/observer/ob_ex_rpc.cpp",
            "src/observer/ob_uniq_task_queue.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_common_mixed_0",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_session_info.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_dbms_job_0",
        language = "c++",
        srcs = [
            "src/observer/dbms_scheduler/ob_dbms_sched_job_utils.cpp",
            "src/observer/dbms_scheduler/ob_dbms_sched_job_executor.cpp",
            "src/observer/dbms_scheduler/ob_dbms_sched_job_master.cpp",
            "src/observer/dbms_scheduler/ob_dbms_sched_table_operator.cpp",
            "src/observer/dbms_scheduler/ob_dbms_sched_service.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_mysql_0",
        language = "c++",
        srcs = [
            "src/observer/mysql/ob_async_cmd_driver.cpp",
            "src/observer/mysql/ob_async_plan_driver.cpp",
            "src/observer/mysql/ob_mysql_end_trans_cb.cpp",
            "src/observer/mysql/ob_mysql_result_set.cpp",
            "src/observer/mysql/ob_query_driver.cpp",
            "src/observer/mysql/ob_sync_cmd_driver.cpp",
            "src/observer/mysql/ob_sync_plan_driver.cpp",
            "src/observer/mysql/obmp_base.cpp",
            "src/observer/mysql/obmp_change_user.cpp",
            "src/observer/mysql/obmp_connect.cpp",
            "src/observer/mysql/obmp_disconnect.cpp",
            "src/observer/mysql/obmp_init_db.cpp",
            "src/observer/mysql/obmp_packet_sender.cpp",
            "src/observer/mysql/obmp_ping.cpp",
            "src/observer/mysql/obmp_query.cpp",
            "src/observer/mysql/obmp_process_info.cpp",
            "src/observer/mysql/obmp_process_kill.cpp",
            "src/observer/mysql/obmp_debug.cpp",
            "src/observer/mysql/obmp_refresh.cpp",
            "src/observer/mysql/obmp_reset_connection.cpp",
            "src/observer/mysql/obmp_statistic.cpp",
            "src/observer/mysql/obmp_stmt_close.cpp",
            "src/observer/mysql/obmp_stmt_execute.cpp",
            "src/observer/mysql/obmp_stmt_fetch.cpp",
            "src/observer/mysql/obmp_stmt_prepare.cpp",
            "src/observer/mysql/obmp_stmt_reset.cpp",
            "src/observer/mysql/obmp_stmt_send_long_data.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_mysql_1",
        language = "c++",
        srcs = [
            "src/observer/mysql/obmp_utils.cpp",
            "src/observer/mysql/obmp_auth_response.cpp",
            "src/observer/mysql/obsm_conn_callback.cpp",
            "src/observer/mysql/obsm_row.cpp",
            "src/observer/mysql/obmp_set_option.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_net_0",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_schema_slot.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_omt_0",
        language = "c++",
        srcs = [
            "src/observer/omt/ob_retry_queue.cpp",
            "src/observer/omt/ob_th_worker.cpp",
            "src/observer/omt/ob_worker_processor.cpp",
            "src/observer/omt/ob_ai_service.cpp",
            "src/observer/omt/ob_server_runtime.cpp",
            "src/observer/omt/ob_server_runtime_controller.cpp",
            "src/observer/omt/ob_srs_service.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_scheduler_0",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_transaction_freeze_checkpoint.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_schema_0",
        language = "c++",
        srcs = [
            "src/observer/schema/ob_schema_service_sql_impl.cpp",
            "src/observer/ob_server_duty_task.cpp",
            "src/observer/ob_system_package_load_task.cpp",
            "src/observer/scheduler/ob_ddl_count_guard.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_vector_index_0",
        language = "c++",
        srcs = [
            "src/observer/vector_index/ob_hybrid_vector_refresh_task.cpp",
            "src/observer/vector_index/ob_ivf_async_task.cpp",
            "src/observer/vector_index/ob_ivf_async_task_executor.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_adaptor.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_scheduler.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_serialize.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_service.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_util.cpp",
            "src/observer/vector_index/ob_plugin_vector_index_utils.cpp",
            "src/observer/vector_index/ob_vector_index_async_task.cpp",
            "src/observer/vector_index/ob_vector_index_async_task_util.cpp",
            "src/observer/vector_index/ob_vector_index_i_task_executor.cpp",
            "src/observer/vector_index/ob_vector_index_ivf_cache_mgr.cpp",
            "src/observer/vector_index/ob_vector_index_ivf_cache_util.cpp",
            "src/observer/vector_index/ob_vector_index_param.cpp",
            "src/observer/vector_index/ob_vector_index_sched_job_utils.cpp",
            "src/observer/vector_index/ob_vector_index_util.cpp",
            "src/observer/vector_index/ob_vector_refresh_transaction.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_0",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_concurrency_object_pool.cpp",
            "src/observer/virtual_table/ob_all_data_type_class_table.cpp",
            "src/observer/virtual_table/ob_all_data_type_table.cpp",
            "src/observer/virtual_table/ob_all_disk_stat.cpp",
            "src/observer/virtual_table/ob_all_plan_cache_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_bad_block_table.cpp",
            "src/observer/virtual_table/ob_all_virtual_compaction_diagnose_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_server_compaction_event_history.cpp",
            "src/observer/virtual_table/ob_all_virtual_compaction_suggestion.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_compaction_info.cpp",
            "src/observer/virtual_table/ob_virtual_table_tablet_iter.cpp",
            "src/observer/virtual_table/ob_all_virtual_dag.cpp",
            "src/observer/virtual_table/ob_all_virtual_dag_warning_history.cpp",
            "src/observer/virtual_table/ob_all_virtual_diag_index_scan.cpp",
            "src/observer/virtual_table/ob_all_virtual_dtl_channel.cpp",
            "src/observer/virtual_table/ob_all_virtual_dtl_memory.cpp",
            "src/observer/virtual_table/ob_all_virtual_engine_table.cpp",
            "src/observer/virtual_table/ob_all_virtual_files_table.cpp",
            "src/observer/virtual_table/ob_all_virtual_id_service.cpp",
            "src/observer/virtual_table/ob_all_virtual_io_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_kvcache_store_memblock.cpp",
            "src/observer/virtual_table/ob_all_virtual_load_data_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_lock_wait_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_long_ops_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_ls_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_timestamp_service.cpp",
            "src/observer/virtual_table/ob_all_virtual_tracepoint_info.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_1",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_transaction_checkpoint.cpp",
            "src/observer/virtual_table/ob_all_virtual_checkpoint.cpp",
            "src/observer/virtual_table/ob_all_virtual_macro_block_marker_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_buffer_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_mds_node_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_mds_event_history.cpp",
            "src/observer/virtual_table/ob_all_virtual_memory_context_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_memstore_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_minor_freeze_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_obj_lock.cpp",
            "src/observer/virtual_table/ob_all_virtual_storage_meta_memory_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_pointer_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_sstable_macro_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_store_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_ps_item_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_ps_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_px_target_monitor.cpp",
            "src/observer/virtual_table/ob_all_virtual_px_worker_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_px_p2p_datahub.cpp",
            "src/observer/virtual_table/ob_all_virtual_dtl_interm_result_monitor.cpp",
            "src/observer/virtual_table/ob_all_virtual_raid_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_server_compaction_progress.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_server_object_pool.cpp",
            "src/observer/virtual_table/ob_all_virtual_server_schema_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_schema_memory.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_2",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_sql_workarea_active.cpp",
            "src/observer/virtual_table/ob_all_virtual_sql_workarea_histogram.cpp",
            "src/observer/virtual_table/ob_all_virtual_sql_workarea_history_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_sql_workarea_memory_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_sys_parameter_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_sys_task_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_table_mgr.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_ddl_kv_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_ddl_sim_point_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_server.cpp",
            "src/observer/virtual_table/ob_all_virtual_sqlite_tables.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_compaction_history.cpp",
            "src/observer/virtual_table/ob_all_virtual_tablet_compaction_progress.cpp",
            "src/observer/virtual_table/ob_all_virtual_io_status.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_lock_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_scheduler_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_ctx_mgr_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_data_table.cpp",
            "src/observer/virtual_table/ob_all_virtual_tx_data.cpp",
            "src/observer/virtual_table/ob_all_virtual_log_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_apply_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_replay_stat.cpp",
            "src/observer/virtual_table/ob_virtual_warning.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_3",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_global_variables.cpp",
            "src/observer/virtual_table/ob_gv_sql.cpp",
            "src/observer/virtual_table/ob_information_check_constraints_table.cpp",
            "src/observer/virtual_table/ob_information_columns_table.cpp",
            "src/observer/virtual_table/ob_information_global_status_table.cpp",
            "src/observer/virtual_table/ob_information_kvcache_table.cpp",
            "src/observer/virtual_table/ob_information_parameters_table.cpp",
            "src/observer/virtual_table/ob_information_partitions_table.cpp",
            "src/observer/virtual_table/ob_information_referential_constraints_table.cpp",
            "src/observer/virtual_table/ob_information_schema_privileges_table.cpp",
            "src/observer/virtual_table/ob_information_session_status_table.cpp",
            "src/observer/virtual_table/ob_information_session_variables_table.cpp",
            "src/observer/virtual_table/ob_information_table_constraints_table.cpp",
            "src/observer/virtual_table/ob_information_table_privileges_table.cpp",
            "src/observer/virtual_table/ob_information_triggers_table.cpp",
            "src/observer/virtual_table/ob_information_user_privileges_table.cpp",
            "src/observer/virtual_table/ob_information_schema_enable_roles_table.cpp",
            "src/observer/virtual_table/ob_mysql_db_table.cpp",
            "src/observer/virtual_table/ob_mysql_proc_table.cpp",
            "src/observer/virtual_table/ob_mysql_user_table.cpp",
            "src/observer/virtual_table/ob_plan_cache_plan_explain.cpp",
            "src/observer/virtual_table/ob_session_variables.cpp",
            "src/observer/virtual_table/ob_show_create_database.cpp",
            "src/observer/virtual_table/ob_show_create_procedure.cpp",
            "src/observer/virtual_table/ob_show_create_table.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_4",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_show_create_trigger.cpp",
            "src/observer/virtual_table/ob_show_database_status.cpp",
            "src/observer/virtual_table/ob_show_grants.cpp",
            "src/observer/virtual_table/ob_show_processlist.cpp",
            "src/observer/virtual_table/ob_table_columns.cpp",
            "src/observer/virtual_table/ob_table_index.cpp",
            "src/observer/virtual_table/ob_virtual_data_access_service.cpp",
            "src/observer/virtual_table/ob_virtual_open_cursor_table.cpp",
            "src/observer/virtual_table/ob_virtual_sql_plan_statistics.cpp",
            "src/observer/virtual_table/ob_virtual_table_iterator.cpp",
            "src/observer/virtual_table/ob_virtual_core_inner_table.cpp",
            "src/observer/virtual_table/ob_virtual_table_iterator_factory.cpp",
            "src/observer/virtual_table/ob_virtual_table_projector.cpp",
            "src/observer/virtual_table/ob_virtual_table_scanner_iterator.cpp",
            "src/observer/virtual_table/ob_all_virtual_dml_stats.cpp",
            "src/observer/virtual_table/ob_virtual_show_trace.cpp",
            "src/observer/virtual_table/ob_all_virtual_memstore_allocator_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_resource_limit.cpp",
            "src/observer/virtual_table/ob_all_virtual_scheduler_running_job.cpp",
            "src/observer/virtual_table/ob_all_virtual_vector_mem_info.cpp",
            "src/observer/virtual_table/ob_show_table_status.cpp",
            "src/observer/virtual_table/ob_virtual_charset.cpp",
            "src/observer/virtual_table/ob_virtual_outline.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_server_virtual_table_5",
        language = "c++",
        srcs = [
            "src/observer/virtual_table/ob_all_virtual_sql_plan.cpp",
            "src/observer/virtual_table/ob_all_virtual_opt_stat_gather_monitor.cpp",
            "src/observer/virtual_table/ob_all_virtual_activity_metrics.cpp",
            "src/observer/virtual_table/ob_all_virtual_nic_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_sys_variable_default_value.cpp",
            "src/observer/virtual_table/ob_all_virtual_vector_index_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_session_ps_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_sql_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_tmp_file.cpp",
            "src/observer/virtual_table/ob_all_virtual_change_stream_refresh_stat.cpp",
            "src/observer/virtual_table/ob_all_virtual_charset.cpp",
            "src/observer/virtual_table/ob_all_virtual_collation.cpp",
            "src/observer/virtual_table/ob_all_virtual_dump_info.cpp",
            "src/observer/virtual_table/ob_all_virtual_memstore_usage.cpp",
            "src/observer/virtual_table/ob_all_virtual_privilege.cpp",
            "src/observer/virtual_table/ob_all_virtual_resource_limit_detail.cpp",
            "src/observer/virtual_table/ob_all_virtual_show_tables.cpp",
            "src/observer/virtual_table/ob_all_virtual_warning.cpp",
            "src/observer/virtual_table/ob_show_tables.cpp",
            "src/observer/virtual_table/ob_virtual_collation.cpp",
            "src/observer/virtual_table/ob_virtual_privilege.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

OBSERVER_MAIN_SOURCES = [
    struct(path = "src/observer/main.cpp", language = "c++", kind = "source"),
    struct(path = "src/observer/ob_command_line_parser.cpp", language = "c++", kind = "source"),
]

OBSERVER_RETRIEVAL_COMPOSITION_SOURCES = [
    struct(path = "src/observer/composition/retrieval/ob_das_legacy_tr_merge_iter.cpp", language = "c++", kind = "source"),
]

OBSERVER_STANDALONE_SOURCES = [
    struct(path = "src/observer/ob_server.cpp", language = "c++", kind = "source"),
    struct(path = "src/observer/ob_service.cpp", language = "c++", kind = "source"),
]

OBSERVER_IGNORED_SOURCES = [
    "report/ob_tablet_meta_checker.cpp",
    "vector_index/ob_vector_index_async_task_scheduler.cpp",
    "virtual_table/ob_all_virtual_all_tables.cpp",
    "virtual_table/ob_all_virtual_concurrent_limit_sql.cpp",
    "virtual_table/ob_all_virtual_outline.cpp",
    "ob_win_service.cpp",
]
