load("//bazel:defs.bzl", "seekdb_module_cc_test")

package(default_visibility = ["//visibility:private"])

seekdb_module_cc_test(
    name = "share_tests",
    srcs = ["server_memory_config_test.cpp"],
    test_hdrs = [],
    module_interface = "//src/share:share_unit_test_interface",
    shard_count = 1,
    unity_size = 1,
)
