#/usr/bin/env python
# -*- coding: utf-8 -*-
"""
syspack_codegen.py
~~~~~~~~~~~~~~~~~~
This script is the configuration center for system packages, with the following functions:
1. Embeds the content of specified system package source code files as strings into `syspack_source.cpp`, which is subsequently compiled and linked into observer
2. Copies the specified system package to the `syspack_release` folder in the compilation directory for subsequent RPM packaging and deployment
NOTE:
1. This script will be automatically called during the compilation phase (make stage) and complete the above three steps, generally no manual invocation is required. It can also be manually invoked using `python2 syspack_codegen.py [option]`.
2. RD only needs to modify the `syspack_config` variable, which is a list where each element is a `SysPackConfig` object containing all information about a system package.
    The current format of the `SysPackConfig` object constructor parameters is:
        `SysPackConfig(group, name, header_file, body_file)`
    Where:
        - group: The grouping of the system package, optional values are `SysPackGroup` enumeration type
        - name: The name of the system package, used to identify the system package in `syspack_source.cpp`
        - header_file: The header file of the system package, must be a `.sql` file
        - body_file: The implementation file of the system package, optional (can be filled with None), must be a `.sql` file
"""

import os
import sys
import argparse
import shutil

# Python 2/3 compatibility: io.open provides consistent interface across versions
try:
    # Python 2.6+ and Python 3
    from io import open
except ImportError:
    # Fallback for older Python 2 (unlikely to be needed)
    import codecs
    def open(filename, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None, closefd=True):
        if encoding is None:
            return codecs.open(filename, mode, errors=errors)
        else:
            return codecs.open(filename, mode, encoding=encoding, errors=errors)

g_script_dir = os.path.dirname(os.path.abspath(__file__))
g_verbose = False

class SysPackGroup:
    MYSQL          = "mysql"
    MYSQL_SPECIAL  = "mysql_special"

class SysPackConfig:
    def __init__(self, group, name, header_file, body_file):
        assert group in [SysPackGroup.MYSQL, SysPackGroup.MYSQL_SPECIAL]
        self.group = group
        assert isinstance(name, str)
        self.name = name
        assert isinstance(header_file, str) and header_file.endswith(".sql")
        self.header_file = header_file
        self.body_file = None
        if body_file:
            assert isinstance(body_file, str) and body_file.endswith(".sql")
            self.body_file = body_file

        self.release_header = self.header_file
        self.release_body = self.body_file

    def export_release_file_list(self):
        return [self.release_header] + ([self.release_body] if self.release_body else [])

    def export_source_file_config(self):
        return "{{\"{}\", \"{}\", {}}},".format(
            self.name,
            self.release_header,
            "\"{}\"".format(self.release_body) if self.release_body else "nullptr")

def install_syspack_files(syspack_config, release_dir):
    file_to_install = []
    for config in syspack_config:
        file_to_install += config.export_release_file_list()
    if g_verbose:
        print("installing syspack files to {}".format(release_dir))
        print("{} files to install: {}".format(len(file_to_install), file_to_install))
    for file in file_to_install:
        src_file = os.path.join(g_script_dir, file)
        dst_file = os.path.join(release_dir, file)
        shutil.copyfile(src_file, dst_file)

def embed_syspack(syspack_config):
    def gen_syspack_file_list(syspack_config, group):
        lst = []
        for config in syspack_config:
            if config.group == group:
                lst.append(config.export_source_file_config())
        return  "int {}_syspack_file_list_length = {};\n".format(group, len(lst)) \
                + "ObSysPackageFile {}_syspack_file_list[] = {{\n".format(group) \
                + "\n".join(lst) + "\n"\
                + "};\n\n"

    syspack_source_file = os.path.join(g_script_dir, "syspack_source.cpp")
    with open(syspack_source_file, "w", encoding="utf8") as f:
        # 1. write header
        f.write("// This file is generated by `syspack_codegen.py`, do not edit it!\n\n"
                "#include <cstdint>\n"
                "#include <utility>\n\n"
                "namespace oceanbase {\n"
                "namespace pl {\n\n"
                "struct ObSysPackageFile {\n"
                "  const char *const package_name;\n"
                "  const char *const package_spec_file_name;\n"
                "  const char *const package_body_file_name;\n"
                "};\n\n")
        # 2. write `xxx_syspack_file_list`
        f.write(gen_syspack_file_list(syspack_config, SysPackGroup.MYSQL))
        f.write(gen_syspack_file_list(syspack_config, SysPackGroup.MYSQL_SPECIAL))
        # 3. write `syspack_source_count`
        release_files = []
        for config in syspack_config:
            release_files += config.export_release_file_list()
        f.write("int64_t syspack_source_count = {};\n".format(len(release_files)))
        # 4. write `syspack_source_contents`
        f.write("std::pair<const char * const, const char* const> syspack_source_contents[] = {\n")
        for file in release_files:
            # 4.1 write file name
            f.write("{{\n"
                    "\"{}\",\n"
                    "R\"sys_pack_del(".format(file))
            # 4.2 write file content
            file_path = os.path.join(g_script_dir, file)
            if os.path.exists(file_path):
                try:
                    with open(file_path, "r", encoding="utf8") as file_content:
                        f.write(file_content.read())
                except Exception as e:
                    sys.stderr.write("failed to embed file: {}\n".format(file_path))
                    sys.stderr.write(str(e) + "\n")
                    sys.exit(1)
            else:
                pass # file not found
            # 4.3 write file end
            f.write(")sys_pack_del\"\n"
                    "},\n")
        f.write("};\n\n")
        # 5. write tail
        f.write("} // namespace pl\n"
                "} // namespace oceanbase\n")

syspack_config = [
    # MySQL
    SysPackConfig(SysPackGroup.MYSQL, "dbms_stats", "dbms_stats_mysql.sql", "dbms_stats_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_scheduler", "dbms_scheduler_mysql.sql", "dbms_scheduler_mysql_body.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_ischeduler", "dbms_ischeduler_mysql.sql", "dbms_ischeduler_mysql_body.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_application", "dbms_application_mysql.sql", "dbms_application_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_session", "dbms_session_mysql.sql", "dbms_session_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_monitor", "dbms_monitor_mysql.sql", "dbms_monitor_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_trusted_certificate_manager", "dbms_trusted_certificate_manager_mysql.sql", "dbms_trusted_certificate_manager_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_ob_limit_calculator", "dbms_ob_limit_calculator_mysql.sql", "dbms_ob_limit_calculator_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_vector", "dbms_vector_mysql.sql", "dbms_vector_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_hybrid_search", "dbms_hybrid_vector_mysql.sql", "dbms_hybrid_vector_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_space", "dbms_space_mysql.sql", "dbms_space_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_ai_service", "dbms_ai_service_mysql.sql", "dbms_ai_service_body_mysql.sql"),
    SysPackConfig(SysPackGroup.MYSQL, "dbms_index_manager", "dbms_index_manager_mysql.sql", "dbms_index_manager_body_mysql.sql"),
]

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="System Package Config Center")
    parser.add_argument("-rd", "--release-dir", type=str, default=None,
                        help="The path to the system package release directory. If empty, installation is not required.")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print verbose information")
    args = parser.parse_args()

    release_dir = args.release_dir
    g_verbose = args.verbose

    # 1. embed syspack files
    embed_syspack(syspack_config)
    # 2. install syspack files
    if release_dir:
        if not os.path.exists(release_dir):
            os.makedirs(release_dir)
        install_syspack_files(syspack_config, release_dir)
