load(
    "//bazel:defs.bzl",
    "seekdb_cc_library",
    "seekdb_cc_test",
    "seekdb_module_cc_test",
    "seekdb_test_interface",
)

package(default_visibility = ["//visibility:private"])

seekdb_test_interface(
    name = "oblib_unit_test_interface",
    deps = [
        "//src/oblib:oblib_unit_test_internal_headers",
    ],
)

seekdb_module_cc_test(
    name = "oblib_tests",
    srcs = [
        "lib/alloc/test_jemalloc_hook.cpp",
        "lib/allocator/test_allocator_facade.cpp",
        "lib/resource/test_memory_quota.cpp",
    ],
    test_hdrs = [],
    module_interface = ":oblib_unit_test_interface",
    unity_size = 1,
    shard_count = 1,
)

seekdb_cc_library(
    name = "_memory_quota_benchmark_impl",
    srcs = ["//tools/testing:memory_quota_benchmark.cpp"],
    implementation_deps = [":oblib_unit_test_interface"],
    testonly = True,
    tags = ["manual"],
    visibility = ["//visibility:private"],
)

seekdb_cc_test(
    name = "memory_quota_benchmark",
    deps = [
        ":_memory_quota_benchmark_impl",
    ],
    linkopts = ["-pthread"],
    tags = ["manual"],
)
