"""Query-owned build topology exposed to its BUILD file."""

QUERY_MYSQL_PROTOCOL_UTIL_SOURCES = [
    "protocol/ob_mysql_protocol_util.cpp",
]

QUERY_SCHEDULER_SOURCES = [
    "scheduler/ob_scheduler_job.cpp",
]

QUERY_VECTOR_EMBEDDING_SOURCES = [
    "vector/ob_vector_embedding_handler.cpp",
]

QUERY_SQL_EXPRESSION_INTERFACE_HEADERS = [
    "api/query/engine/expr/ob_sql_expression.h",
]

QUERY_API_INTERFACE_HEADERS = [
    "api/query/das/ob_block_max_spec_access.h",
    "api/query/das/ob_das_id_protocol.h",
    "api/query/das/ob_das_iter_access.h",
    "api/query/das/ob_fts_eval_node_access.h",
    "api/query/engine/aggregate/ob_aggregate_util.h",
    "api/query/engine/basic/ob_batch_result_holder.h",
    "api/query/engine/basic/ob_encoded_sort_row.h",
    "api/query/engine/basic/ob_external_pushdown_filter.h",
    "api/query/engine/basic/ob_pushdown_filter.h",
    "api/query/engine/basic/ob_row_to_expr_projector.h",
    "api/query/engine/basic/ob_spill_batch_spool.h",
    "api/query/engine/basic/ob_spill_row_store.h",
    "api/query/engine/cmd/ob_ddl_execution.h",
    "api/query/engine/cmd/ob_load_data_parser.h",
    "api/query/engine/cmd/ob_load_data_stat.h",
    "api/query/engine/expr/ob_ai_model_resolver.h",
    "api/query/engine/expr/ob_arithmetic_overflow.h",
    "api/query/engine/expr/ob_array_expr_utils.h",
    "api/query/engine/expr/ob_decimal_int_scale.h",
    "api/query/engine/expr/ob_expr.h",
    "api/query/engine/expr/ob_expr_array_map.h",
    "api/query/engine/expr/ob_expr_bm25.h",
    "api/query/engine/expr/ob_expr_cmp_func.h",
    "api/query/engine/expr/ob_expr_extra_info_factory.h",
    "api/query/engine/expr/ob_expr_in.h",
    "api/query/engine/expr/ob_expr_lob_utils.h",
    "api/query/engine/expr/ob_expr_operator.h",
    "api/query/engine/expr/ob_expr_res_type.h",
    "api/query/engine/expr/ob_expr_util.h",
    "api/query/engine/expr/ob_i_expr_extra_info.h",
    "api/query/engine/ob_batch_rows.h",
    "api/query/engine/ob_exec_context_access.h",
    "api/query/engine/ob_io_event_observer.h",
    "api/query/engine/ob_operator.h",
    "api/query/engine/ob_operator_reg.h",
    "api/query/engine/ob_phy_operator_type.h",
    "api/query/engine/ob_serializable_function.h",
    "api/query/engine/px/ob_px_basic_info.h",
    "api/query/engine/px/ob_px_op_size_factor.h",
    "api/query/engine/px/ob_px_tablet_range.h",
    "api/query/engine/px/p2p_datahub/ob_small_hashset.h",
    "api/query/engine/vector/ob_bitmap_null_vector_base.h",
    "api/query/engine/vector/ob_continuous_base.h",
    "api/query/engine/vector/ob_continuous_format.h",
    "api/query/engine/vector/ob_discrete_base.h",
    "api/query/engine/vector/ob_discrete_format.h",
    "api/query/engine/vector/ob_fixed_length_base.h",
    "api/query/engine/vector/ob_fixed_length_format.h",
    "api/query/engine/vector/ob_i_vector.h",
    "api/query/engine/vector/ob_uniform_base.h",
    "api/query/engine/vector/ob_uniform_format.h",
    "api/query/engine/vector/ob_vector_base.h",
    "api/query/engine/vector/static_check_utils.h",
    "api/query/engine/vector/type_traits.h",
    "api/query/monitor/ob_monitor_node.h",
    "api/query/monitor/ob_ra_queue.h",
    "api/query/ob_i_active_snapshot_service.h",
    "api/query/ob_sql_define.h",
    "api/query/ob_sql_name_service.h",
    "api/query/optimizer/ob_opt_default_stat.h",
    "api/query/optimizer/ob_optimizer_algo_defs.h",
    "api/query/optimizer/ob_optimizer_location_defs.h",
    "api/query/optimizer/stat/ob_opt_column_stat.h",
    "api/query/optimizer/stat/ob_opt_ds_stat.h",
    "api/query/optimizer/stat/ob_opt_osg_column_stat.h",
    "api/query/optimizer/stat/ob_opt_table_stat.h",
    "api/query/optimizer/stat/ob_optimizer_stat_service.h",
    "api/query/optimizer/stat/ob_stat_define.h",
    "api/query/optimizer/stat/ob_stat_item.h",
    "api/query/parser/ob_item_type.h",
    "api/query/parser/parse_node.h",
    "api/query/plan_cache/ob_lib_cache_register.h",
    "api/query/resolver/ob_partition_type_policy.h",
    "api/query/resolver/ob_raw_expr_traits.h",
    "api/query/resolver/ob_schema_lookup.h",
    "api/query/session/ob_deadlock_session.h",
    "api/query/session/ob_free_session_ctx.h",
    "api/query/session/ob_inner_sql_connection_access.h",
    "api/query/session/ob_local_session_var.h",
    "api/query/session/ob_session_access.h",
    "api/query/session/ob_session_inner_sql.h",
    "api/query/tablelock/ob_table_lock_runtime.h",
]

QUERY_SQL_PARSER_TYPE_HEADERS = [
    "api/query/parser/ob_item_type.h",
    "api/query/parser/parse_node.h",
]
