CREATE FUNCTION seekdb_char_count(input_text TEXT)
RETURNS BIGINT
DETERMINISTIC
NO SQL
SQL SECURITY INVOKER
RETURN CHAR_LENGTH(input_text);

CREATE FUNCTION seekdb_byte_count(input_text TEXT)
RETURNS BIGINT
DETERMINISTIC
NO SQL
SQL SECURITY INVOKER
RETURN LENGTH(input_text);
