/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated by cbindgen from the config crate's C ABI. */

#ifndef CONFIG_H_
#define CONFIG_H_

#include <stdint.h>

typedef struct ConfigError {
  uint32_t line;
  uint8_t after_replace;
  char message[512];
} ConfigError;

typedef int (*ConfigCheckCallback)(void *context);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int config_supported(const char *path, struct ConfigError *error);

int config_update_internal_state(const char *path,
                                 const char *name,
                                 const char *value,
                                 struct ConfigError *error);

int config_update_checked(const char *path,
                          const char *name,
                          const char *value,
                          uint8_t reset,
                          ConfigCheckCallback callback,
                          void *context,
                          struct ConfigError *error);

int config_load_active(const char *path, uint8_t startup, struct ConfigError *error);

int config_bootstrap_set(const char *name, const char *value, struct ConfigError *error);

int config_save_bootstrap(const char *path, struct ConfigError *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CONFIG_H_ */
