-- Copyright (c) 2026 OceanBase.
-- Licensed under the Apache License, Version 2.0 (the "License");
--
-- Database-scoped SQL objects backed by the implementation-only GIS module.
-- Optional arities use overloads, not DEFAULT NULL or SQL RETURN wrappers.
-- SQL aliases bind canonical implementation IDs and own independent routines.

CREATE FUNCTION `st_point`(arg1 DOUBLE, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_point' LANGUAGE C;

CREATE FUNCTION `st_makeenvelope`(arg1 DOUBLE, arg2 DOUBLE, arg3 DOUBLE, arg4 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makeenvelope' LANGUAGE C;

CREATE FUNCTION `st_makepoint`(arg1 DOUBLE, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `st_makepoint`(arg1 DOUBLE, arg2 DOUBLE, arg3 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `st_linestring`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_linestring' LANGUAGE C;

CREATE FUNCTION `st_polygon`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_polygon' LANGUAGE C;

CREATE FUNCTION `st_multipoint`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multipoint' LANGUAGE C;

CREATE FUNCTION `st_multilinestring`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multilinestring' LANGUAGE C;

CREATE FUNCTION `st_multipolygon`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multipolygon' LANGUAGE C;

CREATE FUNCTION `st_geometrycollection`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometrycollection' LANGUAGE C;

CREATE FUNCTION `st_geomcollection`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomcollection' LANGUAGE C;

CREATE FUNCTION `st_transform`(arg1 GEOMETRY, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_transform' LANGUAGE C;

CREATE FUNCTION `spatial_cellid`(arg1 GEOMETRY)
RETURNS BIGINT UNSIGNED
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.spatial_cellid' LANGUAGE C;

CREATE FUNCTION `spatial_mbr`(arg1 GEOMETRY)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.spatial_mbr' LANGUAGE C;

CREATE FUNCTION `_st_geohash`(arg1 GEOMETRY)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geohash' LANGUAGE C;

CREATE FUNCTION `_st_geohash`(arg1 GEOMETRY, arg2 BIGINT)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geohash' LANGUAGE C;

CREATE FUNCTION `st_x`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_x' LANGUAGE C;

CREATE FUNCTION `st_y`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_y' LANGUAGE C;

CREATE FUNCTION `st_latitude`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_latitude' LANGUAGE C;

CREATE FUNCTION `st_longitude`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_longitude' LANGUAGE C;

CREATE FUNCTION `st_srid`(arg1 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_srid' LANGUAGE C;

CREATE FUNCTION `st_aswkb`(arg1 GEOMETRY)
RETURNS LONGBLOB
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_aswkb' LANGUAGE C;

CREATE FUNCTION `st_asbinary`(arg1 GEOMETRY)
RETURNS LONGBLOB
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asbinary' LANGUAGE C;

CREATE FUNCTION `_st_geometrytype`(arg1 GEOMETRY)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.geometrytype' LANGUAGE C;

CREATE FUNCTION `st_isvalid`(arg1 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_isvalid' LANGUAGE C;

CREATE FUNCTION `st_astext`(arg1 GEOMETRY)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_astext' LANGUAGE C;

CREATE FUNCTION `st_aswkt`(arg1 GEOMETRY)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_aswkt' LANGUAGE C;

CREATE FUNCTION `st_geomfromwkb`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromwkb' LANGUAGE C;

CREATE FUNCTION `st_geomfromwkb`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromwkb' LANGUAGE C;

CREATE FUNCTION `st_geometryfromwkb`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometryfromwkb' LANGUAGE C;

CREATE FUNCTION `st_geometryfromwkb`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometryfromwkb' LANGUAGE C;

CREATE FUNCTION `_st_setsrid`(arg1 GEOMETRY, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_setsrid' LANGUAGE C;

CREATE FUNCTION `st_geomfromtext`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromtext' LANGUAGE C;

CREATE FUNCTION `st_geomfromtext`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromtext' LANGUAGE C;

CREATE FUNCTION `st_geometryfromtext`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometryfromtext' LANGUAGE C;

CREATE FUNCTION `st_geometryfromtext`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometryfromtext' LANGUAGE C;

CREATE FUNCTION `st_area`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_area' LANGUAGE C;

CREATE FUNCTION `st_length`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_length' LANGUAGE C;

CREATE FUNCTION `st_distance`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_distance' LANGUAGE C;

CREATE FUNCTION `st_equals`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_equals' LANGUAGE C;

CREATE FUNCTION `st_intersects`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_intersects' LANGUAGE C;

CREATE FUNCTION `st_contains`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_contains' LANGUAGE C;

CREATE FUNCTION `st_within`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_within' LANGUAGE C;

CREATE FUNCTION `st_covers`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_covers' LANGUAGE C;

CREATE FUNCTION `st_touches`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_touches' LANGUAGE C;

CREATE FUNCTION `st_crosses`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_crosses' LANGUAGE C;

CREATE FUNCTION `st_overlaps`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_overlaps' LANGUAGE C;

CREATE FUNCTION `st_dwithin`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_dwithin' LANGUAGE C;

CREATE FUNCTION `_st_asewkb`(arg1 GEOMETRY)
RETURNS LONGBLOB
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asewkb' LANGUAGE C;

CREATE FUNCTION `_st_asewkt`(arg1 GEOMETRY)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asewkt' LANGUAGE C;

CREATE FUNCTION `_st_geomfromewkb`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromewkb' LANGUAGE C;

CREATE FUNCTION `_st_geomfromewkb`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromewkb' LANGUAGE C;

CREATE FUNCTION `_st_geomfromewkt`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromewkt' LANGUAGE C;

CREATE FUNCTION `_st_geomfromewkt`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomfromewkt' LANGUAGE C;

CREATE FUNCTION `_st_geogfromtext`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geogfromtext' LANGUAGE C;

CREATE FUNCTION `_st_geogfromtext`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geogfromtext' LANGUAGE C;

CREATE FUNCTION `_st_geographyfromtext`(arg1 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geographyfromtext' LANGUAGE C;

CREATE FUNCTION `_st_geographyfromtext`(arg1 LONGBLOB, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geographyfromtext' LANGUAGE C;

CREATE FUNCTION `_st_iscollection`(arg1 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_iscollection' LANGUAGE C;

CREATE FUNCTION `_st_numinteriorrings`(arg1 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_numinteriorrings' LANGUAGE C;

CREATE FUNCTION `st_asgeojson`(arg1 GEOMETRY)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asgeojson' LANGUAGE C;

CREATE FUNCTION `st_asgeojson`(arg1 GEOMETRY, arg2 DOUBLE)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asgeojson' LANGUAGE C;

CREATE FUNCTION `st_asgeojson`(arg1 GEOMETRY, arg2 DOUBLE, arg3 DOUBLE)
RETURNS LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asgeojson' LANGUAGE C;

CREATE FUNCTION `st_distance_sphere`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_distance_sphere' LANGUAGE C;

CREATE FUNCTION `st_distance_sphere`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_distance_sphere' LANGUAGE C;

CREATE FUNCTION `st_centroid`(arg1 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_centroid' LANGUAGE C;

CREATE FUNCTION `_st_pointonsurface`(arg1 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_pointonsurface' LANGUAGE C;

CREATE FUNCTION `_st_transform`(arg1 GEOMETRY, arg2 BIGINT)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_priv_transform' LANGUAGE C;

CREATE FUNCTION `_st_transform`(arg1 GEOMETRY, arg2 BIGINT, arg3 LONGBLOB)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_priv_transform' LANGUAGE C;

CREATE FUNCTION `st_buffer`(arg1 GEOMETRY, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_buffer' LANGUAGE C;

CREATE FUNCTION `st_buffer`(arg1 GEOMETRY, arg2 DOUBLE, VARIADIC arg3 LONGBLOB[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_buffer' LANGUAGE C;

CREATE FUNCTION `_st_buffer`(arg1 GEOMETRY, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_priv_buffer' LANGUAGE C;

CREATE FUNCTION `_st_buffer`(arg1 GEOMETRY, arg2 DOUBLE, VARIADIC arg3 LONGBLOB[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_priv_buffer' LANGUAGE C;

CREATE FUNCTION `_st_clipbybox2d`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_clipbybox2d' LANGUAGE C;

CREATE FUNCTION `st_union`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_union' LANGUAGE C;

CREATE FUNCTION `st_difference`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_difference' LANGUAGE C;

CREATE FUNCTION `st_symdifference`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_symdifference' LANGUAGE C;

CREATE FUNCTION `_st_asmvtgeom`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asmvtgeom' LANGUAGE C;

CREATE FUNCTION `_st_asmvtgeom`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asmvtgeom' LANGUAGE C;

CREATE FUNCTION `_st_asmvtgeom`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE, arg4 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asmvtgeom' LANGUAGE C;

CREATE FUNCTION `_st_asmvtgeom`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE, arg4 DOUBLE, arg5 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_asmvtgeom' LANGUAGE C;

CREATE FUNCTION `_st_makevalid`(arg1 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makevalid' LANGUAGE C;

CREATE FUNCTION `_st_makevalid`(arg1 GEOMETRY, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makevalid' LANGUAGE C;

CREATE FUNCTION `st_buffer_strategy`(arg1 LONGBLOB)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_buffer_strategy' LANGUAGE C;

CREATE FUNCTION `st_buffer_strategy`(arg1 LONGBLOB, arg2 DOUBLE)
RETURNS VARCHAR(65535) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_buffer_strategy' LANGUAGE C;

CREATE FUNCTION `_st_bestsrid`(arg1 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_bestsrid' LANGUAGE C;

CREATE FUNCTION `_st_bestsrid`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_bestsrid' LANGUAGE C;

CREATE FUNCTION `point`(arg1 DOUBLE, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_point' LANGUAGE C;

CREATE FUNCTION `_st_point`(arg1 DOUBLE, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `_st_point`(arg1 DOUBLE, arg2 DOUBLE, arg3 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `_st_makepoint`(arg1 DOUBLE, arg2 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `_st_makepoint`(arg1 DOUBLE, arg2 DOUBLE, arg3 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makepoint' LANGUAGE C;

CREATE FUNCTION `_st_makeenvelope`(arg1 DOUBLE, arg2 DOUBLE, arg3 DOUBLE, arg4 DOUBLE)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_makeenvelope' LANGUAGE C;

CREATE FUNCTION `linestring`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_linestring' LANGUAGE C;

CREATE FUNCTION `polygon`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_polygon' LANGUAGE C;

CREATE FUNCTION `multipoint`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multipoint' LANGUAGE C;

CREATE FUNCTION `multilinestring`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multilinestring' LANGUAGE C;

CREATE FUNCTION `multipolygon`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_multipolygon' LANGUAGE C;

CREATE FUNCTION `geometrycollection`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geometrycollection' LANGUAGE C;

CREATE FUNCTION `geomcollection`(VARIADIC arg1 GEOMETRY[])
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_geomcollection' LANGUAGE C;

CREATE FUNCTION `area`(arg1 GEOMETRY)
RETURNS DOUBLE
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_area' LANGUAGE C;

CREATE FUNCTION `centroid`(arg1 GEOMETRY)
RETURNS GEOMETRY
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_centroid' LANGUAGE C;

CREATE FUNCTION `_st_covers`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_covers' LANGUAGE C;

CREATE FUNCTION `_st_equals`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_equals' LANGUAGE C;

CREATE FUNCTION `_st_touches`(arg1 GEOMETRY, arg2 GEOMETRY)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_touches' LANGUAGE C;

CREATE FUNCTION `_st_dwithin`(arg1 GEOMETRY, arg2 GEOMETRY, arg3 DOUBLE)
RETURNS BIGINT
DETERMINISTIC NO SQL SQL SECURITY INVOKER
AS 'MODULE_PATHNAME', 'org.seekdb.gis.function.st_dwithin' LANGUAGE C;
