"""Exact fine-grained dependencies for SQL Unity compile groups.

Generated from each Unity member's recursive src/sql include closure. Traversal
stops at Share's public seam, where each included header is mapped to its unique
fine-grained owner target. Direct third-party includes use the same per-group
assignment instead of leaking broad bundles through SQL's public interface.
The group partition is validated at analysis time.
"""

def _materialize_runtime_group_deps(groups):
    actual = {group.name: True for group in groups}
    result = {}
    for group_name in actual:
        result[group_name] = (
            []
            if group_name in _SQL_RUNTIME_SHARE_FREE_GROUPS + _SQL_RUNTIME_SPARSE_SHARE_GROUPS
            else list(_SQL_RUNTIME_COMMON_SHARE_DEPS)
        )
    covered = {
        name: True
        for name in (
            _SQL_RUNTIME_SHARE_FREE_GROUPS +
            _SQL_RUNTIME_SPARSE_SHARE_GROUPS +
            _SQL_RUNTIME_COMMON_ONLY_GROUPS
        )
    }
    for dep, consumers in _SQL_RUNTIME_EXTRA_DEP_CONSUMERS.items():
        for group_name in consumers:
            if group_name in _SQL_RUNTIME_SHARE_FREE_GROUPS:
                fail("Share-free SQL Unity group %s has extra dependency %s" % (group_name, dep))
            result[group_name] = result.get(group_name, []) + [dep]
            covered[group_name] = True
    unknown = sorted([name for name in covered if name not in actual])
    missing = sorted([name for name in actual if name not in covered])
    if unknown or missing:
        fail("SQL runtime Share dependency map differs from Unity inventory: unknown=%s missing=%s" % (unknown, missing))
    return result

def _materialize_assignments(groups, assignments, family):
    actual = {group.name: True for group in groups}
    result = {}
    for assignment in assignments:
        for group_name in assignment.groups:
            if group_name in result:
                fail("%s has duplicate dependency assignment for %s" % (family, group_name))
            result[group_name] = assignment.deps
    unknown = sorted([name for name in result if name not in actual])
    missing = sorted([name for name in actual if name not in result])
    if unknown or missing:
        fail("%s dependency map differs from Unity inventory: unknown=%s missing=%s" % (family, unknown, missing))
    return result

_SQL_RUNTIME_COMMON_SHARE_DEPS = [
    '//src/share:autoincrement_runtime',
    '//src/share:catalog_access',
    '//src/share:cluster_version_interface',
    '//src/share:collection_types',
    '//src/share:config',
    '//src/share:core_types',
    '//src/share:ddl_protocol',
    '//src/share:debug_sync_interface',
    '//src/share:error_codes',
    '//src/share:est_row_count_record',
    '//src/share:execution_contracts',
    '//src/share:geo_cast_interface',
    '//src/share:geo_types',
    '//src/share:interrupt_runtime',
    '//src/share:location',
    '//src/share:memory_support',
    '//src/share:pl_integer_type',
    '//src/share:rpc_dispatch',
    '//src/share:runtime_context',
    '//src/share:schema_access',
    '//src/share:schema_entities',
    '//src/share:schema_model_interface',
    '//src/share:schema_registry',
    '//src/share:scn_interface',
    '//src/share:statement_type',
    '//src/share:system_variable_metadata',
    '//src/share:tablet_autoincrement_types',
    '//src/share:tenant_runtime',
    '//src/share:timezone_runtime',
]

_SQL_RUNTIME_SHARE_FREE_GROUPS = [
    'ob_sql_engine_vector_base_0',
    'ob_sql_engine_vector_cmp_0',
    'ob_sql_engine_vector_fixed_0',
    'ob_sql_engine_vector_uniform_0',
]

_SQL_RUNTIME_SPARSE_SHARE_GROUPS = [
    'ob_sql_engine_vector_continuous_0',
]

_SQL_RUNTIME_COMMON_ONLY_GROUPS = [
]

_SQL_RUNTIME_EXTRA_DEP_CONSUMERS = {
    # Third-party owners are assigned only to Unity groups whose recursive
    # SQL-owned include closure reaches those headers.  Keeping these out of
    # sql_runtime_interface prevents every SQL action and every interface
    # consumer from inheriting all third-party header bundles.
    '@seekdb_3rd_headers//:boost_headers': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_1',
    ],
    '@seekdb_3rd_headers//:curl_headers': [
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_15',
    ],
    '@seekdb_3rd_headers//:fast_float_headers': [
        'ob_sql_engine_expr_1',
    ],
    '@seekdb_3rd_headers//:icu_headers': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_resolver_dml_0',
        'ob_sql_session_0',
    ],
    '@seekdb_3rd_headers//:openssl_headers': [
        'ob_sql_common_0',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_5',
        'ob_sql_engine_expr_13',
    ],
    '//src/share:_generated_inner_table_headers': [
        'ob_sql_engine_0',
        'ob_sql_engine_cmd_1',
    ],
    '//src/share:ai_endpoint_interface': [
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_15',
        'ob_sql_engine_expr_2',
    ],
    '//src/share:cache': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_common_mixed_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_12',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_4',
        'ob_sql_engine_expr_5',
        'ob_sql_engine_expr_6',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_engine_vector_discrete_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_hybrid_search_0',
        'ob_sql_monitor_0',
        'ob_sql_plan_cache_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dcl_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_resolver_ddl_2',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'ob_sql_rewrite_0',
        'ob_sql_rewrite_1',
        'ob_sql_session_0',
    ],
    '//src/share:cluster_topology': [
        'ob_sql_common_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_executor_0',
        'ob_sql_resolver_cmd_0',
    ],
    '//src/share:config_parser_interface': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_monitor_0',
        'ob_sql_plan_cache_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_rewrite_0',
        'ob_sql_rewrite_1',
    ],
    '//src/share:datum': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_core_0',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_plan_cache_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'sql_runtime_standalone_0',
        'sql_runtime_standalone_1',
        'sql_runtime_standalone_2',
        'sql_runtime_standalone_3',
        'sql_runtime_standalone_4',
    ],
    '//src/share:ddl_coordination': [
        'ob_sql_common_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_table_0',
    ],
    '//src/share:device_manager_interface': [
        'ob_sql_engine_basic_0',
        'ob_sql_engine_cmd_0',
    ],
    '//src/share:diagnostics': [
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_executor_0',
        'ob_sql_session_0',
    ],
    '//src/share:external_storage': [
        'ob_sql_printer_0',
    ],
    '//src/share:geo_algorithms': [
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_7',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_expr_9',
        'ob_sql_engine_vector_continuous_0',
    ],
    '//src/share:geo_serialization': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_core_0',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_expr_9',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'sql_runtime_standalone_0',
        'sql_runtime_standalone_1',
        'sql_runtime_standalone_2',
        'sql_runtime_standalone_3',
        'sql_runtime_standalone_4',
    ],
    '//src/share:geo_visitors': [
        'ob_sql_engine_expr_7',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_expr_9',
    ],
    '//src/share:io': [
        'ob_sql_code_generator_0',
        'ob_sql_common_mixed_0',
        'ob_sql_engine_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_px_0',
        'ob_sql_executor_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dml_0',
    ],
    '//src/share:json_access': [
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_15',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_4',
        'ob_sql_engine_expr_5',
    ],
    '//src/share:lob_runtime': [
        'ob_sql_engine_0',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_8',
    ],
    '//src/share:module_data_protocol': [
        'ob_sql_engine_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_executor_0',
        'ob_sql_resolver_cmd_0',
    ],
    '//src/share:object_cast': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_engine_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_12',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_engine_expr_15',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_4',
        'ob_sql_engine_expr_5',
        'ob_sql_engine_expr_6',
        'ob_sql_engine_expr_7',
        'ob_sql_engine_expr_9',
        'ob_sql_resolver_0',
        'ob_sql_resolver_expr_0',
        'ob_sql_rewrite_0',
        'ob_sql_session_0',
    ],
    '//src/share:object_cast_runtime_interface': [
        'ob_sql_common_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_rewrite_0',
    ],
    '//src/share:roaringbitmap': [
        'ob_sql_das_1',
    ],
    '//src/share:rpc_message_types': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_common_mixed_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_core_0',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_12',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_4',
        'ob_sql_engine_expr_5',
        'ob_sql_engine_expr_6',
        'ob_sql_engine_expr_7',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_hybrid_search_0',
        'ob_sql_monitor_0',
        'ob_sql_plan_cache_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dcl_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_resolver_ddl_2',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'ob_sql_rewrite_0',
        'ob_sql_rewrite_1',
        'ob_sql_session_0',
        'sql_runtime_standalone_0',
        'sql_runtime_standalone_1',
        'sql_runtime_standalone_2',
        'sql_runtime_standalone_3',
        'sql_runtime_standalone_4',
    ],
    '//src/share:schema_foundation_types': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_common_mixed_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_cmd_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_10',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_12',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_14',
        'ob_sql_engine_expr_15',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_3',
        'ob_sql_engine_expr_4',
        'ob_sql_engine_expr_5',
        'ob_sql_engine_expr_6',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_hybrid_search_0',
        'ob_sql_monitor_0',
        'ob_sql_plan_cache_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dcl_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_resolver_ddl_2',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'ob_sql_rewrite_0',
        'ob_sql_rewrite_1',
        'ob_sql_session_0',
    ],
    '//src/share:schema_persistence': [
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
    ],
    '//src/share:sequence_option': [
        'ob_sql_common_mixed_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_executor_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
    ],
    '//src/share:sequence_runtime': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_0',
    ],
    '//src/share:seekdb_runtime_foundation': [
        'ob_sql_resolver_0',
    ],
    '//src/share:sql_persistence_support': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_core_0',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_cmd_1',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_resolver_expr_0',
        'ob_sql_tablelock_0',
        'sql_runtime_standalone_0',
        'sql_runtime_standalone_1',
        'sql_runtime_standalone_2',
        'sql_runtime_standalone_3',
        'sql_runtime_standalone_4',
    ],
    '//src/share:srs_provider_interface': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_das_0',
        'ob_sql_das_1',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_7',
        'ob_sql_engine_vector_continuous_0',
        'ob_sql_engine_expr_8',
        'ob_sql_engine_expr_9',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_engine_table_0',
        'ob_sql_engine_vector_discrete_0',
        'ob_sql_executor_0',
        'ob_sql_executor_1',
        'ob_sql_plan_cache_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_rewrite_0',
        'sql_runtime_standalone_3',
    ],
    '//src/share:storage_cache_policy': [
        'ob_sql_common_0',
        'ob_sql_engine_cmd_1',
        'ob_sql_executor_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dcl_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_resolver_ddl_2',
        'ob_sql_resolver_dml_0',
    ],
    '//src/share:table_access_runtime': [
        'ob_sql_tablelock_0',
    ],
    '//src/share:table_load_protocol': [
        'ob_sql_common_mixed_0',
        'ob_sql_engine_cmd_0',
        'ob_sql_executor_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_0',
        'ob_sql_resolver_cmd_0',
        'ob_sql_resolver_dml_0',
    ],
    '//src/share:table_runtime': [
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_ddl_1',
        'ob_sql_resolver_ddl_2',
    ],
    '//src/share:tablet_autoincrement_interface': [
        'ob_sql_das_0',
        'ob_sql_engine_dml_0',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_expr_7',
    ],
    '//src/share:tenant_role_transition_interface': [
        'ob_sql_engine_cmd_0',
    ],
    '//src/share:unit_topology': [
        'ob_sql_code_generator_0',
        'ob_sql_common_0',
        'ob_sql_das_0',
        'ob_sql_dtl_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_expr_1',
        'ob_sql_engine_expr_11',
        'ob_sql_engine_expr_13',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_join_0',
        'ob_sql_engine_pdml_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'ob_sql_engine_set_0',
        'ob_sql_executor_0',
        'ob_sql_printer_0',
        'ob_sql_resolver_dml_0',
    ],
    '//src/share:utility_types': [
        'ob_sql_common_0',
        'ob_sql_resolver_ddl_0',
        'ob_sql_resolver_dml_0',
        'ob_sql_session_0',
    ],
    '//src/share:vector': [
        'ob_sql_code_generator_0',
        'ob_sql_engine_0',
        'ob_sql_engine_1',
        'ob_sql_engine_aggregate_core_0',
        'ob_sql_engine_aggregate_groupby_0',
        'ob_sql_engine_basic_1',
        'ob_sql_engine_expr_2',
        'ob_sql_engine_join_0',
        'ob_sql_engine_px_0',
        'ob_sql_engine_px_1',
        'sql_runtime_standalone_1',
        'sql_runtime_standalone_2',
        'sql_runtime_standalone_3',
        'sql_runtime_standalone_4',
    ],
    '//src/share:worker_runtime': [
        'ob_sql_dtl_0',
    ],
}

_SQL_RUNTIME_WITHOUT_PASS_SHARE_DEP_ASSIGNMENTS = [
    struct(
        groups = [
            'sql_runtime_extra_10',
            'sql_runtime_extra_11',
            'sql_runtime_extra_13',
            'sql_runtime_extra_14',
            'sql_runtime_extra_15',
            'sql_runtime_extra_16',
            'sql_runtime_extra_17',
            'sql_runtime_extra_18',
            'sql_runtime_extra_19',
            'sql_runtime_extra_2',
            'sql_runtime_extra_20',
            'sql_runtime_extra_4',
            'sql_runtime_extra_5',
            'sql_runtime_extra_6',
            'sql_runtime_extra_7',
            'sql_runtime_extra_8',
            'sql_runtime_extra_9',
        ],
        deps = [
            '//src/share:datum',
        ],
    ),
    struct(
        groups = [
        ],
        deps = [
            '@seekdb_3rd_headers//:fast_float_headers',
            '//src/share:autoincrement_runtime',
            '//src/share:catalog_access',
            '//src/share:cluster_version_interface',
            '//src/share:collection_types',
            '//src/share:config',
            '//src/share:core_types',
            '//src/share:datum',
            '//src/share:ddl_protocol',
            '//src/share:debug_sync_interface',
            '//src/share:error_codes',
            '//src/share:execution_contracts',
            '//src/share:geo_cast_interface',
            '//src/share:geo_types',
            '//src/share:interrupt_runtime',
            '//src/share:location',
            '//src/share:memory_support',
            '//src/share:object_cast',
            '//src/share:pl_integer_type',
            '//src/share:rpc_dispatch',
            '//src/share:runtime_context',
            '//src/share:schema_access',
            '//src/share:schema_entities',
            '//src/share:schema_model_interface',
            '//src/share:schema_registry',
            '//src/share:scn_interface',
            '//src/share:statement_type',
            '//src/share:system_variable_metadata',
            '//src/share:tablet_autoincrement_types',
            '//src/share:tenant_runtime',
            '//src/share:timezone_runtime',
        ],
    ),
    struct(
        groups = [
            'sql_runtime_extra_12',
            'sql_runtime_extra_3',
        ],
        deps = [
        ],
    ),
    struct(
        groups = [
            'sql_runtime_extra_0',
        ],
        deps = [
            '//src/share:autoincrement_runtime',
            '//src/share:catalog_access',
            '//src/share:cluster_version_interface',
            '//src/share:collection_types',
            '//src/share:config',
            '//src/share:core_types',
            '//src/share:ddl_protocol',
            '//src/share:debug_sync_interface',
            '//src/share:error_codes',
            '//src/share:execution_contracts',
            '//src/share:geo_cast_interface',
            '//src/share:geo_types',
            '//src/share:interrupt_runtime',
            '//src/share:json_access',
            '//src/share:lob_runtime',
            '//src/share:location',
            '//src/share:memory_support',
            '//src/share:object_cast',
            '//src/share:object_cast_runtime_interface',
            '//src/share:pl_integer_type',
            '//src/share:rpc_dispatch',
            '//src/share:runtime_context',
            '//src/share:schema_access',
            '//src/share:schema_entities',
            '//src/share:schema_model_interface',
            '//src/share:schema_registry',
            '//src/share:scn_interface',
            '//src/share:srs_provider_interface',
            '//src/share:statement_type',
            '//src/share:system_variable_metadata',
            '//src/share:tablet_autoincrement_types',
            '//src/share:tenant_runtime',
            '//src/share:timezone_runtime',
        ],
    ),
    struct(
        groups = [
            'sql_runtime_extra_1',
        ],
        deps = [
            '//src/share:autoincrement_runtime',
            '//src/share:catalog_access',
            '//src/share:cluster_version_interface',
            '//src/share:collection_types',
            '//src/share:config',
            '//src/share:core_types',
            '//src/share:ddl_protocol',
            '//src/share:debug_sync_interface',
            '//src/share:error_codes',
            '//src/share:execution_contracts',
            '//src/share:geo_cast_interface',
            '//src/share:geo_types',
            '//src/share:interrupt_runtime',
            '//src/share:location',
            '//src/share:memory_support',
            '//src/share:object_cast',
            '//src/share:object_cast_runtime_interface',
            '//src/share:pl_integer_type',
            '//src/share:rpc_dispatch',
            '//src/share:runtime_context',
            '//src/share:schema_access',
            '//src/share:schema_entities',
            '//src/share:schema_model_interface',
            '//src/share:schema_registry',
            '//src/share:scn_interface',
            '//src/share:statement_type',
            '//src/share:system_variable_metadata',
            '//src/share:tablet_autoincrement_types',
            '//src/share:tenant_runtime',
            '//src/share:timezone_runtime',
        ],
    ),
    struct(
        groups = [
        ],
        deps = [
            '//src/share:autoincrement_runtime',
            '//src/share:cluster_version_interface',
            '//src/share:collection_types',
            '//src/share:config',
            '//src/share:core_types',
            '//src/share:ddl_protocol',
            '//src/share:debug_sync_interface',
            '//src/share:error_codes',
            '//src/share:execution_contracts',
            '//src/share:geo_cast_interface',
            '//src/share:location',
            '//src/share:memory_support',
            '//src/share:object_cast',
            '//src/share:pl_integer_type',
            '//src/share:runtime_context',
            '//src/share:schema_access',
            '//src/share:schema_entities',
            '//src/share:schema_model_interface',
            '//src/share:schema_registry',
            '//src/share:scn_interface',
            '//src/share:statement_type',
            '//src/share:system_variable_metadata',
            '//src/share:tenant_runtime',
            '//src/share:timezone_runtime',
        ],
    ),
    struct(
        groups = [
        ],
        deps = [
            '@seekdb_3rd_headers//:fast_float_headers',
            '//src/share:autoincrement_runtime',
            '//src/share:catalog_access',
            '//src/share:cluster_version_interface',
            '//src/share:collection_types',
            '//src/share:config',
            '//src/share:core_types',
            '//src/share:ddl_protocol',
            '//src/share:debug_sync_interface',
            '//src/share:error_codes',
            '//src/share:execution_contracts',
            '//src/share:geo_cast_interface',
            '//src/share:geo_types',
            '//src/share:interrupt_runtime',
            '//src/share:location',
            '//src/share:memory_support',
            '//src/share:object_cast',
            '//src/share:pl_integer_type',
            '//src/share:rpc_dispatch',
            '//src/share:runtime_context',
            '//src/share:schema_access',
            '//src/share:schema_entities',
            '//src/share:schema_model_interface',
            '//src/share:schema_registry',
            '//src/share:scn_interface',
            '//src/share:statement_type',
            '//src/share:system_variable_metadata',
            '//src/share:tablet_autoincrement_types',
            '//src/share:tenant_runtime',
            '//src/share:timezone_runtime',
        ],
    ),
]

_SQL_RUNTIME_SIMD_SHARE_DEP_ASSIGNMENTS = [
    struct(
        groups = [
            'ob_sql_simd_common_0',
        ],
        deps = [
            '//src/share:config',
            '//src/share:runtime_context',
        ],
    ),
]

def sql_runtime_group_share_deps(groups):
    return _materialize_runtime_group_deps(groups)

def sql_runtime_without_pass_group_share_deps(groups):
    return _materialize_assignments(groups, _SQL_RUNTIME_WITHOUT_PASS_SHARE_DEP_ASSIGNMENTS, "SQL runtime without pass")

def sql_runtime_simd_group_share_deps(groups):
    return _materialize_assignments(groups, _SQL_RUNTIME_SIMD_SHARE_DEP_ASSIGNMENTS, "SQL SIMD runtime")
