"""Storage-owned build topology exposed to its BUILD file."""

load(
    ":storage_header_inventory.bzl",
    _STORAGE_INTERFACE_CLOSURE_HEADERS = "STORAGE_INTERFACE_CLOSURE_HEADERS",
    _STORAGE_PRIVATE_HEADERS = "STORAGE_PRIVATE_HEADERS",
    _STORAGE_PUBLIC_HEADER_ROOTS = "STORAGE_PUBLIC_HEADER_ROOTS",
)
load(
    ":storage_module_sources.bzl",
    _storage_singleton_unity_groups = "storage_singleton_unity_groups",
    _storage_validate_source_inventory = "storage_validate_source_inventory",
)
load(
    ":storage_source_inventory.bzl",
    _STORAGE_EXTRA_SOURCES = "STORAGE_EXTRA_SOURCES",
    _STORAGE_SIMD_UNITY_GROUPS = "STORAGE_SIMD_UNITY_GROUPS",
    _STORAGE_STANDALONE_SOURCES = "STORAGE_STANDALONE_SOURCES",
    _STORAGE_TABLET_AUTOINCREMENT_STATE_SOURCES = "STORAGE_TABLET_AUTOINCREMENT_STATE_SOURCES",
    _STORAGE_UNITY_GROUPS = "STORAGE_UNITY_GROUPS",
)

STORAGE_EXTRA_SOURCES = _STORAGE_EXTRA_SOURCES
STORAGE_INTERFACE_CLOSURE_HEADERS = _STORAGE_INTERFACE_CLOSURE_HEADERS
STORAGE_PRIVATE_HEADERS = _STORAGE_PRIVATE_HEADERS
STORAGE_PUBLIC_HEADER_ROOTS = _STORAGE_PUBLIC_HEADER_ROOTS
STORAGE_SIMD_UNITY_GROUPS = _STORAGE_SIMD_UNITY_GROUPS
STORAGE_STANDALONE_SOURCES = _STORAGE_STANDALONE_SOURCES
STORAGE_TABLET_AUTOINCREMENT_STATE_SOURCES = _STORAGE_TABLET_AUTOINCREMENT_STATE_SOURCES
STORAGE_UNITY_GROUPS = _STORAGE_UNITY_GROUPS

storage_singleton_unity_groups = _storage_singleton_unity_groups
storage_validate_source_inventory = _storage_validate_source_inventory
