load("//bazel:defs.bzl", "seekdb_module_cc_test")

package(default_visibility = ["//visibility:private"])

seekdb_module_cc_test(
    name = "standby_tests",
    srcs = glob(["**/*.cpp"]),
    test_hdrs = glob(["**/*.h"], allow_empty = True),
    module_interface = "//src/standby:standby_unit_test_interface",
)
