using System.Diagnostics;
using System.IO;
using System.ServiceProcess;
using System.Text;
using Microsoft.Win32;

namespace seekdbConfigurator;

/// <summary>Applies wizard settings by writing seekdb.cnf and invoking seekdb.exe (same idea as tools/windows/seekdb_manage.ps1).</summary>
public sealed class ConfiguratorEngine
{
    private const string RegistryKeyPath = @"Software\SeekDB";

    public static string? FindSeekdbExe()
    {
        var exeDir = Path.GetDirectoryName(Environment.ProcessPath);
        if (string.IsNullOrEmpty(exeDir))
            return null;

        var candidates = new[]
        {
            Path.Combine(exeDir, "seekdb.exe"),
            Path.GetFullPath(Path.Combine(exeDir, "..", "bin", "seekdb.exe")),
            Path.GetFullPath(Path.Combine(exeDir, "..", "..", "bin", "seekdb.exe")),
        };

        foreach (var c in candidates)
        {
            if (File.Exists(c))
                return c;
        }

        return null;
    }

    /// <summary>Typical MSI layout: installation root containing bin/ and etc/</summary>
    public static string? FindDefaultEtcCnf(string seekdbExe)
    {
        var bin = Path.GetDirectoryName(seekdbExe);
        if (string.IsNullOrEmpty(bin))
            return null;
        var installRoot = Path.GetFullPath(Path.Combine(bin, ".."));
        var cnf = Path.Combine(installRoot, "etc", "seekdb.cnf");
        return File.Exists(cnf) ? cnf : null;
    }

    public static void WriteCnf(string targetCnfPath, WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        cfg.ApplyConfigTypePresets();
        var baseDir = cfg.BaseDirForCnf;
        var sb = new StringBuilder();
        sb.AppendLine("# seekdb Configuration File (generated by seekdb Configurator)");
        sb.AppendLine("# These parameters are permanently valid");
        sb.AppendLine($"base-dir={baseDir}");
        sb.AppendLine($"data-dir={baseDir}/store");
        sb.AppendLine($"redo-dir={baseDir}/store/redo");
        sb.AppendLine();
        sb.AppendLine("# Valid at initialization / runtime as applicable");
        sb.AppendLine($"port={cfg.Port}");
        sb.AppendLine($"cpu_count={cfg.CpuCount}");
        sb.AppendLine($"memory_limit={cfg.MemoryLimit}");
        File.WriteAllText(targetCnfPath, sb.ToString(), Encoding.UTF8);
    }

    public static void EnsureDirectories(WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        var root = cfg.DataDirectory.TrimEnd('\\');
        Directory.CreateDirectory(root);
        Directory.CreateDirectory(Path.Combine(root, "store"));
        Directory.CreateDirectory(Path.Combine(root, "store", "redo"));
    }

    public static int RunProcess(string fileName, string arguments, Action<string>? onLine = null)
    {
        var psi = new ProcessStartInfo(fileName, arguments)
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        using var p = new Process { StartInfo = psi };
        p.OutputDataReceived += (_, e) => { if (e.Data != null) onLine?.Invoke(e.Data); };
        p.ErrorDataReceived += (_, e) => { if (e.Data != null) onLine?.Invoke(e.Data); };
        p.Start();
        p.BeginOutputReadLine();
        p.BeginErrorReadLine();
        p.WaitForExit();
        return p.ExitCode;
    }

    public static void TryAddFirewallRule(int port, Action<string> log)
    {
        var ruleName = $"seekdb TCP {port}";
        var psi = new ProcessStartInfo("netsh", $"advfirewall firewall add rule name=\"{ruleName}\" dir=in action=allow protocol=TCP localport={port}")
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
        };
        try
        {
            using var p = Process.Start(psi);
            p?.WaitForExit();
            log($"Firewall rule '{ruleName}' add exit code: {p?.ExitCode ?? -1}");
        }
        catch (Exception ex)
        {
            log($"Firewall: {ex.Message}");
        }
    }

    public static bool NeedsInit(WizardConfig cfg)
    {
        cfg.NormalizeDataDirectory();
        var baseDir = cfg.DataDirectory.TrimEnd('\\');
        var meta = Path.Combine(baseDir, ".meta");
        var dataDir = Path.Combine(baseDir, "store");
        if (File.Exists(meta))
            return false;
        if (!Directory.Exists(dataDir))
            return true;
        return !Directory.EnumerateFileSystemEntries(dataDir).Any();
    }

    public static int RunInit(string seekdbExe, WizardConfig cfg, string cnfPath, Action<string>? log)
    {
        cfg.ApplyConfigTypePresets();
        var args = new StringBuilder();
        args.Append($"--base-dir=\"{cfg.BaseDirForCnf}\" --nodaemon");
        args.Append($" --port={cfg.Port}");
        args.Append($" --parameter memory_limit={cfg.MemoryLimit}");
        args.Append($" --parameter cpu_count={cfg.CpuCount}");

        log?.Invoke($"{seekdbExe} {args}");
        return RunProcess(seekdbExe, args.ToString(), log);
    }

    public static int RunInstallService(string seekdbExe, WizardConfig cfg, string cnfPath, Action<string>? log)
    {
        cfg.ApplyConfigTypePresets();
        var args = new StringBuilder();
        args.Append($"--install-service {cfg.ServiceName} --base-dir=\"{cfg.BaseDirForCnf}\"");
        args.Append($" --port={cfg.Port}");
        args.Append($" --parameter memory_limit={cfg.MemoryLimit}");
        args.Append($" --parameter cpu_count={cfg.CpuCount}");
        log?.Invoke($"{seekdbExe} {args}");
        return RunProcess(seekdbExe, args.ToString(), log);
    }

    public static void SetServiceStartMode(string serviceName, bool autoStart)
    {
        var mode = autoStart ? "auto" : "demand";
        RunProcess("sc.exe", $"config {serviceName} start= {mode}");
    }

    public static void TryStartService(string serviceName, Action<string> log)
    {
        try
        {
            using var sc = new ServiceController(serviceName);
            if (sc.Status == ServiceControllerStatus.Running)
            {
                log("Service already running.");
                return;
            }
            sc.Start();
            sc.WaitForStatus(ServiceControllerStatus.Running, TimeSpan.FromMinutes(2));
            log("Service started.");
        }
        catch (Exception ex)
        {
            log($"Start service: {ex.Message}");
        }
    }

    // ── Registry: persist install info for removal ──────────────

    public static void SaveInstallInfo(string dataDirectory, string serviceName, int port)
    {
        try
        {
            using var key = Registry.LocalMachine.CreateSubKey(RegistryKeyPath);
            key.SetValue("DataDirectory", dataDirectory);
            key.SetValue("ServiceName", serviceName);
            key.SetValue("Port", port, RegistryValueKind.DWord);
        }
        catch { }
    }

    public static (string? dataDir, string? serviceName, int port) LoadInstallInfo()
    {
        try
        {
            using var key = Registry.LocalMachine.OpenSubKey(RegistryKeyPath);
            if (key == null) return (null, null, 2881);
            var dataDir = key.GetValue("DataDirectory") as string;
            var serviceName = key.GetValue("ServiceName") as string;
            var port = key.GetValue("Port") is int p ? p : 2881;
            return (dataDir, serviceName, port);
        }
        catch { return (null, null, 2881); }
    }

    public static void CleanRegistry()
    {
        try { Registry.LocalMachine.DeleteSubKeyTree(RegistryKeyPath, false); }
        catch { }
    }

    // ── Removal helpers (use sc.exe to avoid ServiceController assembly
    //    loading issues in single-file publish) ──────────────────

    public static string? FindSeekdbServiceName()
    {
        try
        {
            var output = new StringBuilder();
            RunProcess("sc.exe", "query type= service state= all",
                line => output.AppendLine(line));
            foreach (var line in output.ToString().Split('\n'))
            {
                var trimmed = line.Trim();
                if (trimmed.StartsWith("SERVICE_NAME:", StringComparison.OrdinalIgnoreCase))
                {
                    var name = trimmed.Substring("SERVICE_NAME:".Length).Trim();
                    if (name.StartsWith("seekdb", StringComparison.OrdinalIgnoreCase))
                        return name;
                }
            }
        }
        catch { }
        return null;
    }

    public static bool ServiceExists(string serviceName)
    {
        return RunProcess("sc.exe", $"query {serviceName}") == 0;
    }

    public static bool TryStopService(string serviceName, Action<string> log)
    {
        log($"Stopping service '{serviceName}'...");
        int rc = RunProcess("sc.exe", $"stop {serviceName}", log);
        if (rc != 0 && rc != 1062)
        {
            log($"sc.exe stop exit code {rc}.");
            return false;
        }
        // Wait for the service to fully stop (poll up to 60 seconds)
        for (int i = 0; i < 30; i++)
        {
            Thread.Sleep(2000);
            var output = new StringBuilder();
            RunProcess("sc.exe", $"query {serviceName}", line => output.AppendLine(line));
            if (output.ToString().Contains("STOPPED", StringComparison.OrdinalIgnoreCase))
            {
                log("Service stopped.");
                return true;
            }
        }
        log("Service stop timed out, proceeding anyway.");
        return true;
    }

    public static bool TryRemoveService(string? seekdbExe, string serviceName, Action<string> log)
    {
        if (seekdbExe != null && File.Exists(seekdbExe))
        {
            var args = $"--remove-service {serviceName}";
            log($"{seekdbExe} {args}");
            int rc = RunProcess(seekdbExe, args, log);
            if (rc == 0) { log("Service removed."); return true; }
            log($"--remove-service exit code {rc}, falling back to sc.exe...");
        }

        int rc2 = RunProcess("sc.exe", $"delete {serviceName}", s => log(s));
        if (rc2 == 0) { log("Service removed via sc.exe."); return true; }
        log($"sc.exe delete exit code {rc2}.");
        return false;
    }

    public static bool TryRemoveFirewallRules(int port, Action<string> log)
    {
        try
        {
            var ruleName = $"seekdb TCP {port}";
            int rc = RunProcess("netsh",
                $"advfirewall firewall delete rule name=\"{ruleName}\"",
                s => log(s));
            log(rc == 0 ? "Firewall rules removed." : "No matching firewall rules found (OK).");
            return true;
        }
        catch (Exception ex)
        {
            log($"Firewall cleanup: {ex.Message}");
            return false;
        }
    }

    public static bool TryRemoveConfigFile(string dataDirectory, Action<string> log)
    {
        try
        {
            var cnfPath = Path.Combine(dataDirectory.TrimEnd('\\'), "etc", "seekdb.cnf");
            if (File.Exists(cnfPath))
            {
                File.Delete(cnfPath);
                log($"Configuration file removed: {cnfPath}");
            }
            else
            {
                log("No configuration file found.");
            }
            return true;
        }
        catch (Exception ex)
        {
            log($"Remove config file: {ex.Message}");
            return false;
        }
    }

    public static bool TryRemoveDataDirectory(string dataDirectory, Action<string> log)
    {
        try
        {
            if (Directory.Exists(dataDirectory))
            {
                Directory.Delete(dataDirectory, true);
                log($"Data directory removed: {dataDirectory}");
            }
            else
            {
                log("Data directory does not exist.");
            }
            return true;
        }
        catch (Exception ex)
        {
            log($"Remove data directory: {ex.Message}");
            return false;
        }
    }
}
