#ifndef OCEANBASE_OBSERVER_VECTOR_INDEX_UTIL_COMPAT_H_
#define OCEANBASE_OBSERVER_VECTOR_INDEX_UTIL_COMPAT_H_

#include "query/vector/ob_vector_index_util.h"

#endif // OCEANBASE_OBSERVER_VECTOR_INDEX_UTIL_COMPAT_H_
