[package]
name = "seekdb-rust-candidate"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
name = "seekdb_rust_candidate"
crate-type = ["cdylib"]

[dependencies]
seekdb-extension = { path = "../../rust/extension-sdk" }

[profile.release]
panic = "unwind"
lto = "thin"
codegen-units = 1
