site_name: OceanBase seekdb Developer Guide
site_url: https://oceanbase.github.io/seekdb
repo_url: https://github.com/oceanbase/seekdb
repo_name: oceanbase/seekdb
docs_dir: developer-guide
plugins:
  - search
  #- material-relative-language-selector
  #- mdpo
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          link: /developer-guide/en/
        - locale: zh
          name: 中文
          build: true
          link: /developer-guide/zh/
  - git-authors
nav:
  - Overview: README.md
  - Get started:
      - Install the toolchain: toolchain.md
      - Build and run: build-and-run.md
      - Android: android.md
      - Homebrew optimization: homebrew.md
  - Development:
      - Coding conventions: coding-convention.md
      - Coding standard: coding-standard.md
      - Unit tests: unittest.md
      - mysqltest: mysqltest.md
      - Debug: debug.md
  - Internals:
      - Logging: logging.md
      - Memory management: memory.md
      - Containers: container.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: en
  features:
    - search.highlight
    - navigation.sections
    - navigation.path
    - navigation.top
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
