set(CPACK_GENERATOR "TGZ")
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_IGNORE_GROUPS ON)
set(CPACK_ARCHIVE_THREADS 1)

include(cmake/Pack.cmake)

if(APPLE)
  execute_process(
    COMMAND sw_vers -productVersion
    OUTPUT_VARIABLE SEEKDB_MACOS_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE SEEKDB_SW_VERS_RESULT)
  if(SEEKDB_SW_VERS_RESULT EQUAL 0 AND
     SEEKDB_MACOS_VERSION MATCHES "^([0-9]+)")
    set(SEEKDB_PACKAGE_SYSTEM "macos${CMAKE_MATCH_1}")
  else()
    set(SEEKDB_PACKAGE_SYSTEM "macos")
  endif()
else()
  string(TOLOWER "${CMAKE_SYSTEM_NAME}" SEEKDB_PACKAGE_SYSTEM)
endif()

set(SEEKDB_TGZ_BASENAME
  "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${SEEKDB_PACKAGE_RELEASE}-${SEEKDB_PACKAGE_SYSTEM}-${ARCHITECTURE}")
set(CPACK_PACKAGE_FILE_NAME "${SEEKDB_TGZ_BASENAME}")
set(CPACK_ARCHIVE_SERVER_FILE_NAME "${SEEKDB_TGZ_BASENAME}")
set(CPACK_ARCHIVE_LIBS_FILE_NAME
  "${CPACK_PACKAGE_NAME}-libs-${CPACK_PACKAGE_VERSION}-${SEEKDB_PACKAGE_RELEASE}-${SEEKDB_PACKAGE_SYSTEM}-${ARCHITECTURE}")

message(STATUS "CPack generator: TGZ")
message(STATUS "CPack components: ${CPACK_COMPONENTS_ALL}")

include(CPack)

add_custom_target(tgz
  COMMAND "${CMAKE_CPACK_COMMAND}" -G TGZ
    --config "${CMAKE_BINARY_DIR}/CPackConfig.cmake"
  DEPENDS seekdb generate_syspack_source
  USES_TERMINAL
  VERBATIM)
