# One verified installation supplies the Windows SQLite headers, import library and DLL.
if(NOT WIN32)
  return()
endif()
set(OB_SQLITE_DIR "${CMAKE_SOURCE_DIR}/build_phase0/sqlite-candidate/install" CACHE PATH
    "SQLite installation built with deps/init/sqlite/build-control.ps1 -Candidate")
file(TO_CMAKE_PATH "${OB_SQLITE_DIR}" OB_SQLITE_DIR)
set(_sqlite_manifest "${OB_SQLITE_DIR}/seekdb-sqlite-install.json")
if(NOT EXISTS "${_sqlite_manifest}")
  message(FATAL_ERROR "Missing SQLite installation identity: ${_sqlite_manifest}; run build.ps1 sqlite-candidate")
endif()
file(READ "${_sqlite_manifest}" _sqlite_identity)
string(JSON _sqlite_version GET "${_sqlite_identity}" version)
string(JSON _sqlite_candidate GET "${_sqlite_identity}" candidate)
string(JSON _sqlite_patch GET "${_sqlite_identity}" candidate_patch_sha256)
file(SHA256 "${CMAKE_SOURCE_DIR}/deps/init/sqlite/local-extended-drive.patch" _sqlite_expected_patch)
if(NOT _sqlite_version STREQUAL "3.51.2" OR NOT _sqlite_candidate
   OR NOT _sqlite_patch STREQUAL _sqlite_expected_patch)
  message(FATAL_ERROR "SQLite installation does not match the required candidate")
endif()
set(_sqlite_files include/sqlite3.h include/sqlite3ext.h include/sqlite3-vcpkg-config.h lib/sqlite3.lib bin/sqlite3.dll share/sqlite3/copyright)
string(JSON _sqlite_count LENGTH "${_sqlite_identity}" files)
if(NOT _sqlite_count EQUAL 6)
  message(FATAL_ERROR "Incomplete SQLite installation identity")
endif()
foreach(_sqlite_index RANGE 0 5)
  list(GET _sqlite_files ${_sqlite_index} _sqlite_required)
  string(JSON _sqlite_name GET "${_sqlite_identity}" files ${_sqlite_index} name)
  string(JSON _sqlite_expected GET "${_sqlite_identity}" files ${_sqlite_index} sha256)
  if(NOT _sqlite_name STREQUAL _sqlite_required)
    message(FATAL_ERROR "Unexpected SQLite installation entry: ${_sqlite_name}")
  endif()
  file(SHA256 "${OB_SQLITE_DIR}/${_sqlite_required}" _sqlite_actual)
  if(NOT _sqlite_actual STREQUAL _sqlite_expected)
    message(FATAL_ERROR "SQLite installation hash mismatch: ${_sqlite_required}")
  endif()
  if(_sqlite_required STREQUAL "bin/sqlite3.dll")
    set(OB_SQLITE_DLL_SHA256 "${_sqlite_actual}" CACHE INTERNAL
        "Verified SQLite DLL hash shared by build and packaging directories" FORCE)
  elseif(_sqlite_required STREQUAL "share/sqlite3/copyright")
    set(OB_SQLITE_LICENSE_SHA256 "${_sqlite_actual}" CACHE INTERNAL
        "Verified SQLite license hash shared by build and packaging directories" FORCE)
  endif()
endforeach()
message(STATUS "Verified SQLite candidate: ${OB_SQLITE_DIR}")
