"""Logservice-owned source and Unity topology."""

LOGSERVICE_UNITY_GROUPS = [
    struct(
        name = "ob_logservice_common_0",
        language = "c++",
        srcs = [
            "src/logservice/ob_append_callback.cpp",
            "src/logservice/ob_log_handler.cpp",
            "src/logservice/ob_log_service.cpp",
            "src/logservice/ob_server_log_block_mgr.cpp",
            "src/logservice/ob_log_monitor.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_logservice_common_mixed_0",
        language = "c++",
        srcs = [
            "src/logservice/applyservice/ob_log_apply_service.cpp",
            "src/logservice/localservice/ob_local_log_handler_set.cpp",
            "src/logservice/replayservice/ob_log_replay_service.cpp",
            "src/logservice/replayservice/ob_replay_handler.cpp",
            "src/logservice/replayservice/ob_replay_status.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_logservice_common_util_0",
        language = "c++",
        srcs = [
            "src/logservice/common_util/ob_log_time_utils.cpp",
            "src/logservice/ob_log_allocator.cpp",
            "src/logservice/ob_log_allocator_mgr.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_logservice_palf_0",
        language = "c++",
        srcs = [
            "src/logservice/palf/block_gc_timer_task.cpp",
            "src/logservice/palf/log_block_handler.cpp",
            "src/logservice/palf/log_block_header.cpp",
            "src/logservice/palf/log_block_mgr.cpp",
            "src/logservice/palf/log_checksum.cpp",
            "src/logservice/palf/log_engine.cpp",
            "src/logservice/palf/log_entry.cpp",
            "src/logservice/palf/log_entry_header.cpp",
            "src/logservice/palf/log_group_entry.cpp",
            "src/logservice/palf/log_group_entry_header.cpp",
            "src/logservice/palf/log_shared_queue_thread.cpp",
            "src/logservice/palf/log_io_task.cpp",
            "src/logservice/palf/log_io_task_cb_thread_pool.cpp",
            "src/logservice/palf/log_io_task_cb_utils.cpp",
            "src/logservice/palf/log_shared_task.cpp",
            "src/logservice/palf/log_io_worker.cpp",
            "src/logservice/palf/log_iterator_storage.cpp",
            "src/logservice/palf/log_loop_thread.cpp",
            "src/logservice/palf/log_meta.cpp",
            "src/logservice/palf/log_meta_entry.cpp",
            "src/logservice/palf/log_meta_entry_header.cpp",
            "src/logservice/palf/log_meta_info.cpp",
            "src/logservice/palf/log_reader.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_logservice_palf_1",
        language = "c++",
        srcs = [
            "src/logservice/palf/log_reader_utils.cpp",
            "src/logservice/palf/log_sliding_window.cpp",
            "src/logservice/palf/log_state_mgr.cpp",
            "src/logservice/palf/log_storage.cpp",
            "src/logservice/palf/log_task.cpp",
            "src/logservice/palf/log_write_buf.cpp",
            "src/logservice/palf/lsn_allocator.cpp",
            "src/logservice/palf/palf_log_buffer.cpp",
            "src/logservice/palf/palf_callback_wrapper.cpp",
            "src/logservice/palf/palf_env.cpp",
            "src/logservice/palf/palf_env_impl.cpp",
            "src/logservice/palf/palf_handle.cpp",
            "src/logservice/palf/palf_handle_impl.cpp",
            "src/logservice/palf/log_cache.cpp",
            "src/logservice/palf/palf_handle_impl_guard.cpp",
            "src/logservice/palf/log_block_pool_interface.cpp",
            "src/logservice/palf/log_mode_mgr.cpp",
            "src/logservice/palf/log_io_utils.cpp",
            "src/logservice/palf/log_io_worker_wrapper.cpp",
            "src/logservice/palf/log_throttle.cpp",
            "src/logservice/palf/log_io_context.cpp",
            "src/logservice/palf/log_io_adapter.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]
